### ISSUE TITLE
OnPressHandler Protocol doesn't like awaitable

### ISSUE THREAD

**Issue by JPHutchins** [beeware/toga#2608] opened 2024-05-29 01:27 UTC
### Describe the bug

Mypy says 

```
Argument "on_press" to "Button" has incompatible type "Callable[[Any], Any]"; expected "OnPressHandler | None"Mypy[arg-type](https://mypy.readthedocs.io/en/latest/_refs.html#code-arg-type)
```

### Steps to reproduce

```python
class App(toga.App):
    def startup(self):
        """Construct and show the Toga application.

        Usually, you would add your application to a main content box.
        We then create a main window (with a name matching the app), and
        show the main window.
        """

        main_box = toga.Box()

        # Create a button
        self._button = toga.Button('Run tests', on_press=self._async_handler)
        main_box.add(self._button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()
    
    async def _async_handler(self, widget) -> None:
        await asyncio.sleep(0.001)
```

### Expected behavior

The Protocol is a union of Callable and Awaitable.  It is handled at runtime by the wrapped_handler function.

### Environment

- Operating System: Windows 11
- Python version: 3.12
- Software versions:
  - Briefcase: 0.3.18
  - Toga: 0.4.4
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment] 2024-05-29 01:32
Closing as a duplicate of #2192; see #2252 for some further discussion about this. 

At least at present, we don't consider full formal MyPy compliance to be a goal for Toga, on the basis that there are some typing patterns that are perfectly legal, but don't fit well into a formal typing setup - and making them comply with strict typing doesn't actually improve readability. 

We're definitely open to suggestions on how this could be addressed - formal MyPy compliance would be great if we could achieve it - but not at the cost of significant degradation in documentation and code clarity.

**Closed by freakboy3742** 2024-05-29 01:32 UTC
Labels: bug
