### ISSUE TITLE
How to change main window content (iOS)

### ISSUE THREAD

**Issue by BrendanSimon** [beeware/toga#773] opened 2020-01-01 13:41 UTC
I'm trying to trial a hierarchical menu system using `DetailedList` (but that's not directly relevant).

<img width="410" alt="toga-main-window-1" src="https://user-images.githubusercontent.com/472245/71641977-273c5b80-2cf8-11ea-9933-31ad28c01236.png">

When the `on_select` method is called, I change the main window content to another detailed list.  The list renders ok, but the iOS frame seems to disappear.

<img width="410" alt="toga-main-window-2" src="https://user-images.githubusercontent.com/472245/71641979-358a7780-2cf8-11ea-8b27-3cbf2edc48f5.png">

Am I changing the window content in the correct manner?  What is the correct way to change the main window content?

```python
import toga
from toga.style import Pack
from toga.style.pack import ( COLUMN, ROW, TOP, BOTTOM, CENTER )

#!============================================================================

class Test_App( toga.App ) :

    def startup( self ) :
        #! Create the main window
        self.main_window = toga.MainWindow( title=self.name )

        count = 20

        data_1 = [
                {   'icon'      : None,
                    'title'     : f'Title # {i}\nAAA # {i}',
                    'subtitle'  : "Test 1 2 3"
                    # 'subtitle'  : "Test 1 2 3\nTesting Testing 1 2 3"
                }
                for i in range( count )
                ]

        detailed_list_box_1 = toga.DetailedList(    id = 'detailed_lsit_box_1',
                                                    data = data_1,
                                                    on_select = self.detailed_list_box_1_on_select,
                                                    style = Pack( padding=10 )
                                                    )

        main_box_1 = toga.Box(  id = 'main_box_1',
                                style = Pack( direction=COLUMN, flex=0 ),
                                # children = [ box_1_scroller, box_2_scroller, box_3_scroller ],
                                children = [ detailed_list_box_1 ],
                                )

        data_2 = [
                {
                    'icon'      : None,
                    'title'     : f'Levle 2.{i}\nAAA # {i}',
                    'subtitle'  : "Pick me pick me !!"
                }
                for i in range( count )
                ]

        detailed_list_box_2 = toga.DetailedList(    id = 'detailed_lsit_box_2',
                                                    data = data_2,
                                                    style = Pack( padding=10 )
                                                    )

        main_box_2 = toga.Box(  id = 'main_box',
                                style = Pack( direction=COLUMN, flex=0 ),
                                children = [ detailed_list_box_2 ],
                                )

        self.main_box_1 = main_box_1
        self.main_box_2 = main_box_2

        #! Show the main window
        self.main_window.content = self.main_box_1
        self.main_window.show()

    #!------------------------------------------------------------------------

    def detailed_list_box_1_on_select( self, widget, row ) :
        self.main_window.content = self.main_box_2
        # self.main_window.show()

#!============================================================================

def main() :
    return Test_App( 'Test App', 'au.com.etrix.test_app' )
```

**Comment by ubuntume** [comment] 2020-02-13 00:00
Same issue on Android. I remember email the author and he said it wasn’t possible at the moment I think.

**Comment by freakboy3742** [comment] 2020-04-25 15:17
I'm going to call this a duplicate of #225 - it isn't an iOS specific problem.

**Closed by freakboy3742** 2020-04-25 15:17 UTC
