### ISSUE TITLE
🐞: Toga's HelloWorld renders incorrectly on elemetnary OS

### ISSUE THREAD

**Issue by joe733** [beeware/toga#933] opened 2020-06-02 13:34 UTC
## Expected Behavior

The [hello world program](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) works smoothly and shows the window like in the [docs](https://toga.readthedocs.io/en/latest/_images/tutorial-0.png).

## Current Behavior

The `button` sticks out of the `box`. The following screenshot can tell better:

![Screenshot from 2020-06-02 18-05-10](https://user-images.githubusercontent.com/38415384/83521412-d2964a00-a4fc-11ea-8f65-04cdaf5f42af.png)

The button with text `Hello world` is seen on the top of and outside title bar.

## Steps to reproduce

1. Create the hello world app as mention in the [docs](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html).
2. Run the app using `$ python -m hello_world`  (if you've named the toga app as `hello_world.py`)
3. See the error. (The button works on click, the rendered UI is incorrect)

**Output**:
```python
hello_world on  master [!?] via 🅒 toga_env took 1m 30s 
⮚.⮚.⮚ python -m hello_world
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
hello
hello
```

## Your Environment

* Python Version (list the specific version number): Python 3.8.3

```python
~ via 🅒 toga_env 
⮚.⮚.⮚ conda info

     active environment : toga_env
    active env location : /home/joe/anaconda3/envs/toga_env
            shell level : 2
       user config file : /home/joe/.condarc
 populated config files : /home/joe/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages : __glibc=2.27
       base environment : /home/joe/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/joe/anaconda3/pkgs
                          /home/joe/.conda/pkgs
       envs directories : /home/joe/anaconda3/envs
                          /home/joe/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/5.3.0-53-generic elementary/5.1.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] <s> macOS - version: </s>
  - [X] Linux - distro: [elementary OS](https://elementary.io/) - version:  5.1.4 Hera
  - [ ] <s> Windows - version: </s>
  - [ ] <s> Other - name:  - version: </s>

![photo_2020-06-02_18-21-28](https://user-images.githubusercontent.com/38415384/83522165-ea220280-a4fd-11ea-9e2a-876f6307aa4c.jpg)

* Toga Version (list the specific version number or git hash):
from `~ via 🅒 toga_env  ⮚.⮚.⮚  conda list`

```python
toga                      0.3.0.dev19              pypi_0    pypi
toga-core                 0.3.0.dev19              pypi_0    pypi
toga-gtk                  0.3.0.dev19              pypi_0    pypi
```

* Toga Target (the type of app you are trying to generate)

  - [ ] <s> android </s>
  - [ ] <s> cocoa </s>
  - [ ] <s> django </s>
  - [X] gtk ([pantheon-desktop](https://en.wikipedia.org/wiki/Elementary_OS#Pantheon_desktop_environment))
  - [ ] <s> iOS </s>
  - [ ] <s> tvOS </s>
  - [ ] <s> watchOS </s>
  - [ ] <s> winforms </s>
  - [ ] <s> win32 </s>
  - [ ] <s> Other (please specify) </s>

---

### Additional Info
- I'm not using any 3rd party GTK+ theme. Everything is default.
- I've enable global GTK dark theme:

```python
~ via 🅒 toga_env 
⮚.⮚.⮚ cat ~/.config/gtk-3.0/settings.ini
[Settings]
gtk-application-prefer-dark-theme=1
```

- The [swithcboard](https://github.com/elementary/switchboard/) you see in the info screenshot has a known [issue:#146](https://github.com/elementary-tweaks/elementary-tweaks/issues/146) and the fix is yet to be rolled out.

> Tell me if I'm missing any critical info here, will be glad to help.

**Comment by freakboy3742** [comment] 2020-06-02 23:31
Thanks for the report. This looks like it's a duplicate of #139, which was resolved really recently; the fix is available in the development version right now, and will be in the 0.3.0.dev20 release. If that fix doesn't work, let us know and I'll reopen the ticket.

**Closed by freakboy3742** 2020-06-02 23:31 UTC
