### ISSUE TITLE
'on_close' not working

### ISSUE THREAD

**Issue by david-ragazzi** [beeware/toga#641] opened 2019-01-25 10:58 UTC
## Expected Behavior
'on_close' event be triggered.

## Current Behavior
The window is hidden but the event is not triggered. Curiously, I also put a timer function to run when the window is open, and when I 'close' the window the function keeps running. It seems that the window is just hidden not closed (its controls are not destructed and thus 'on_close' is not triggered). 

## Steps to reproduce

Run this piece of code:

```
def on_close_handler(widget):
    print("on_close fired")

window = toga.Window()
window.on_close = on_close_handler
window.show()
```

## Your Environment

* Python Version
3.6

* Operating System and Version

  - [ ] macOS - version: 
  - [x] Linux - distro: Mint  - version: 16
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [X] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other

**Comment by david-ragazzi** [comment] 2019-01-25 12:20
Now I remember that when I run through the script via briefcase:

```python setup.py linux -s```

I got a compatibilty warning with toga version during preparation but it run the code without problem (maybe the `on_close`). I don't remember the exact version that it claims but I have installed the lastest toga (0.3.dev11) and briefcase use 0.3.dev8. I'll provide the exact message. But I would like know if `on_close` event is implemented in fact or it's just a future feature.

**Comment by freakboy3742** [comment] 2019-01-26 02:51
@david-ragazzi The feature exists, but I make no guarantees that it works on every platform :-)

on-close is a feature where I wouldn't be at all surprised if there are bugs, because each platform has it's own subtle dance to coordinate firing the event at a time when the window still exists, but is in the process of closing. Differentiating between "window close button has been pressed", "window is closing", "window *has* closed" and "application is closing" can be difficult, and on Windows it's a particular problem because of the way Windows operates.

It's made *more* difficult by the fact that we don't have an automated test suite for GUI operations, so it's easy for regressions to leak in.

**Comment by stantonxu** [comment] 2020-06-07 21:59
I cannot reproduce this problem on my Debian or Ubuntu. Window closed properly.

I tried to add below line into the create() function of MainWindow class in app.py for GTK, which actually cause some exception.

```        self.native.connect("destroy", Gtk.main_quit)

**Comment by freakboy3742** [comment] 2022-03-29 06:17
We've done a lot of reworking of `on_close()` since this was reported, so I'm closing this as fixed; if you are still having problems, please open a new ticket with specifics.

**Closed by freakboy3742** 2022-03-29 06:17 UTC
