### ISSUE TITLE
Table on windows does not fill container

### ISSUE THREAD

**Issue by LunaMeadows** [beeware/toga#1811] opened 2023-03-11 14:55 UTC
### Describe the bug

When creating a Table on windows, it will only go for 100 which is the MIN_WIDTH. Setting the width does not affect it either. On linux it will fill the containers width but not on windows.

### Steps to reproduce

Add a Table to a box

### Expected behavior

Table contents will fill container

### Screenshots

![image](https://user-images.githubusercontent.com/38821657/224491427-db7a997d-98a6-4271-a2e4-0a1e3fda50f9.png)

### Environment

- Operating System: Windows 10
- Python version: 3.11
- Software versions:
  - Briefcase:
  - Toga: 0.3.1
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment] 2023-03-12 22:54
Can I ask you to clarify some details - in particular, the Toga version you've reported. Toga 0.3.1 hasn't been released; if you mean that you've installed the development version, we need to know the exact commit (which is why `toga.__version__` will report a `0.3.1.dev77+g4f6f7ab9` or similar). This is important detail because it can indicate whether the problem is due to a recent commit, or has been fixed in a recent commit.

If you're on Toga 0.3.0 - then can I ask you to try with a recent development version, because this may have been addressed with a recent change to root widget layout.

**Comment by freakboy3742** [comment] 2023-03-12 22:56
It also helps if you provide the specific example code that you've used to manufacture the problem - although this is a simple example, it will make a difference whether your app uses the table as the content of the main window, or you're using a box as the main content, which contains a Table.

**Comment by LunaMeadows** [comment] 2023-03-12 23:13
Apologizes, it is toga 0.3.0. I can test the dev version as well as get some sample code later tonight once I get off of work.

**Comment by LunaMeadows** [comment] 2023-03-14 11:42
![image](https://user-images.githubusercontent.com/38821657/224990198-f8e09784-10b2-4dda-99e9-f3964b437d30.png)
This was done with the '0.3.1.dev77+g4f6f7ab9' version. The issue seems to persist. The same thing happens even if I set the main window content to the table instead of the box as well.
`
import toga
from toga.style.pack import COLUMN, Pack, ROW, CENTER

class togaApp(toga.App):

    def startup(self):
        self.main_window = toga.MainWindow()
        box = toga.Box(id='main_content', style=Pack(direction=COLUMN, width=400))
        table = toga.Table(headings=['Testing'], data=['Cows'])
        box.add(table)
        self.main_window.content = box
        return self


def main():
    return togaApp("First App", "org.beeware.helloworld")


if __name__ == "__main__":
    main().main_loop()
`

**Comment by freakboy3742** [comment] 2023-03-20 05:51
Apologies for the delay - I was at a conference last week, and didn't have access to my Windows testing setup. I'm now back at my desk, and I can't see any problem.

As programmed, this will produce a widget that is 400 pixels wide, and 100 pixels tall (the default minimum height for the widget, when packed inside a column box). If you drop the explicit width from the box, the table will fill the horizontal space on the widget; if you make the table `flex=1`, the table will fill the entire horizontal space.

The flex is required because you're packing the table inside a box; the box is trying to be as small as it can be, which compresses the table. By making the table flexible, it grows to fill the available space. This wouldn't be needed if the table was the top-level widget in the container.

The table only has 1 column, and by default, the column will be as wide as the content in the column (in this case, there's no content, so the column is as wide as the title).

What behavior are you expecting to see?

**Comment by LunaMeadows** [comment] 2023-03-20 22:59
I was expecting to see the column be as wide as the box but as you said that is not what the code is supposed to do. It seems this issue may be with Ubuntu/linux and not windows if that is the case as in Ubuntu the column is as wide as the box and not based on the content of the column like it is on windows.

**Comment by LunaMeadows** [comment] 2023-03-20 23:01
![image](https://user-images.githubusercontent.com/38821657/226484073-f17aac69-d055-4cc6-8f14-3000fd545a8b.png)
This is a screenshot of the same code ran in Ubuntu. As you can see the column is as wide as the box which is what I was expecting to see on windows.

**Comment by freakboy3742** [comment] 2023-03-20 23:33
That's a detail of the Windows implementation of Table. By default, columns on Winforms are only as wide as the data in the column. As a general rule, you *shouldn't* expect pixel-perfect reproduction of behavior between platforms; you should expect *functional* equivalence.

So - this isn't a *bug* in the strictest sense, but it is a cosmetic detail that could be altered. I'd agree that having empty space in a table doesn't make a whole lot of sense, and altering the winforms Table implementation so that the columns consume all available space in the table would be desirable.

**Closed** 2023-08-28 01:49 UTC
Labels: enhancement, awaiting details, windows
