### ISSUE TITLE
Launch PDF file

### ISSUE THREAD

**Issue by ikiex** [beeware/toga#1940] opened 2023-05-12 16:28 UTC
### Describe the bug

Hi, I am creating a simple app to open a pdf but I cannot find documentation on how to launch the pdf, I have tried with jnius but when installing it throws me this error
running build_ext
  cythoning jnius/jnius.pyx to jnius/jnius.c
  building 'jnius' extension
  error: CCompiler.compile: Chaquopy cannot compile native code.

### Expected behavior

launch PDF file in android

### Environment

- Operating System:Linux 
- Python version:3.9
- Software versions:
  - Briefcase:briefcase.2023_05_12-11_24_47.build
  - Toga: toga-android~=0.3.1
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment] 2023-05-13 01:15
PyJNIus is a module with a binary component, so you'll need to mange the process of building a binary wheel.

However, PyJNIus is probably not the tool you want in this case. PyJNIus is the Java binding library used by Kivy; BeeWare uses Chaquopy. The APIs for accessing the native Java platform on Android are very similar; [see the Chaquopy documentation for details.](https://chaquo.com/chaquopy/doc/current/python.html).

There's not currently any Toga API for opening a PDF; you'll need to use native system APIs if you want to do that.

Closing this ticket because it's not a bug in Toga.

**Closed by freakboy3742** 2023-05-13 01:15 UTC
Labels: bug

**Comment by mhsmith** [comment] 2023-05-13 09:39
@ikiex: Jnius is simply a Python/Java interface, so I'm not sure how you think it would help you open a PDF. If you were planning to call [`startActivity`](https://developer.android.com/reference/android/content/Context#startActivity(android.content.Intent)), then you can do that in Toga by calling `self._impl.native.startActivity`, where `self` is the `toga.App` object. The `Intent` passed to this function can be created using the Chaquopy API, whose documentation is linked above.
