### ISSUE TITLE
Adding All CSS/CSS-like properties

### ISSUE THREAD

**Issue by bambier** [beeware/toga#2282] opened 2023-12-16 16:07 UTC
### What is the problem or limitation you are having?

I tried to add [Material Design ](https://m3.material.io/) same as [KivyMD](https://kivymd.readthedocs.io/en/1.1.1/).
When I want to use CSS properties such as `outline`, `box-shadow`, etc. I noticed that BeeWare doesn't support these features.
Also I didn't find any good documentation but [DOC1](https://docs.beeware.org/en/latest/tutorial/tutorial-2.html) and [DOC2](https://github.com/beeware/toga/blob/main/docs/reference/style/pack.rst) that shows how to use properties such as `box-shadow`!

### Describe the solution you'd like

I spent VERY LOOOOOOOOOOOOOOOOOOOOOOONG time to notice what happens in code and how BeeWare core exactly knows which property and values are acceptable (Actually I'm not sure yet if that I'm doing right or not).

I changed **_Packing_** style and made it dynamic which you can find in my [repo1](https://github.com/bambier/travertino/blob/main/src/travertino/css_properties.py) and [repo2](https://github.com/bambier/toga/blob/b35859b09a138fc1e1ef58beaf3bdbee46a2043c/core/src/toga/style/pack.py#L919)

So I opened this **issue** to know if I'm correct or not! because working on [repo1](https://github.com/bambier/travertino/blob/main/src/travertino/css_properties.py) is really boring and annoying due to that very long time taken to finishing it. 😰

### Describe alternatives you've considered

I've NOOOOO idea what I'm doing 😐

**Comment by freakboy3742** [comment] 2023-12-17 05:38
I'm going to mark this as WONTFIX - for a couple of reasons.

The first is that Toga is designed to be style-agnostic. In practice, there's currently only 1 style language - Pack - but conceptually, any style language that implements the `toga.style.TogaApplicator()` interface could be used. The intention is that you could replace Toga's built-in Pack implementation with any other style implementation (be that CSS-based or not), and Toga would still work. As a result, adding more CSS tags to Toga is the wrong way to go about things. 

Adding tags to Travertino is also the wrong approach - Travertino is a common base that defines a box model and essential properties on which you could build *any* style engine. Adding CSS3 terms to Travertino is missing the point of Travertino.

This may seem like an odd architectural choice, but it's because of the second reason: Pack is, by design, *not* a full CSS engine. It's designed to be enough of a CSS subset to get simple layouts working. The long term goal is to move away from Pack, and to [Colosseum](https://github.com/beeware/colosseum/) - which *is* a full CSS3 layout engine. If you want to work on a full, browser independent CSS implementation, Colosseum is where you should be contributing.

But then there's the third reason: Toga will intentionally *not* honour all of CSS - and again, this is by design. We want to honour the full CSS3 box model, grid and flex box models (the "layout" parts of CSS)- but when it comes to borders, shadows and other "appearance" aspects of CSS, Toga will be very selective in what it honours.

This is because Toga is *explicitly*, and by design, a platform-native GUI toolkit. It uses *native* widgets, to render a *native* look and feel. A Toga app on Windows looks like a Windows app; on Android, it looks like an Android app; on macOS, it looks like a macOS app; and so on. To that end, tags like "box-shadow" will, generally speaking, *not* be honoured, because they're trying to impose a look and feel on widget appearance that *is not* native. If you have a burning desire to give buttons a specific appearance that will be shared across all platforms, you're going to be disappointed - because this is what Toga is specifically *not* trying to do.

Material is explicitly *not* a native look and feel. It's a Google look and feel, primarily intended for use in websites, but also used by Android. Material apps *do not* look or feel native on iOS, macOS, GTK or Windows. To that end, proposing a "Material backend for Toga" is a bit like proposing that you will cook a really nice rare steak for vegans - an otherwise reasonable culinary choice, except that the audience has explicitly told you they're not interested in that option.

Let me be explicit here: If you want your app to look the same (be that following Material design, or anything else) on every platform, **Toga is not the toolkit you want**. Consistent appearance between platforms is a design choice; but it's not one that Toga is interested in or in a position to support. If you want this, using Kivy would be my suggestion - it's explicitly *not* a platform native toolkit, so it will be much closer aligned to your needs. 

Toga's backend API would, in theory, allow you to define a "Material" backend for Toga... but then, you'd need to implement that backend for every platform where you wanted the toolkit to work. You're effectively going to be duplicating *all* of Toga. If you're motivated to do that, then go right ahead, I guess... but it's not going to be a small task. We're *definitely* not going to be adding any Material aspects to Toga's existing backends - except of course, for the Android backend, where Material *is* the native look and feel.

If, despite all this, you're eager to work on a CSS implementation - then I encourage you to look into Colosseum. It hasn't had much attention for the last couple of years, because we've been focussing on getting Toga's core widget functionality working. However, it's still very much on my TODO list eventually.

**Closed by freakboy3742** 2023-12-17 05:38 UTC
Labels: enhancement
