### ISSUE TITLE
[Winforms] [Switch widget] is_on triggers on_toggle handler on initialization

### ISSUE THREAD

**Issue by UncleGoogle** [beeware/toga#788] opened 2020-01-19 18:25 UTC
## Expected Behavior
Creating switch should not trigger `on_toggle` callback when `is_on` is set to True before running `main_loop`

## Current Behavior
`on_toggle` is called when `is_on` in Switch constructor is set to True

## Steps to reproduce

```python
import toga
from toga.style.pack import Pack, COLUMN


def on_toggle(widget):
    print('handler')

def build(app):
    box = toga.Box()

    switch = toga.Switch('Switch', on_toggle=on_toggle, is_on=True)
    box.add(switch)

    return box

def main():
    return toga.App('First App', 'org.beeware.helloworld', startup=build)

if __name__ == '__main__':
    main().main_loop()
```

'handler' is printed just after running this code from console

## Your Environment
* Python version
`3.7.3`

* OS
  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: **Windows 7**
  - [ ] Other - name:  - version:

* Toga Version
`0.3.0.dev18`

* Toga Target (the type of app you are trying to generate)

  - [x] winforms or win32 (I don't know)

**Comment by saroad2** [comment] 2020-09-27 17:39
Cannot reproduce this bug, therefore closing it.
Please feel free to reopen if it does.

**Closed by saroad2** 2020-09-27 17:39 UTC
Labels: bug, up-for-grabs
