### ISSUE TITLE
It would be nice to have a clickable URL Widget in iOS

### ISSUE THREAD

**Issue by massenz** [beeware/toga#1237] opened 2021-03-29 06:55 UTC
**Is your feature request related to a problem? Please describe.**

It is currently not possible to redirect the user to a URL in the browser, either directly (e.g., when they click a button) or indirectly (i.e., when they click a URL in a label).

Adding a Label with a URL has no effect and it's even more frustatring for the user, as they can't select and copy & paste the URL into a browser address bar.

**Describe the solution you'd like**

Ideally, there should be both a `URL` widget, as well as a `open_url(url)` method (e.g., in the `App` object) so that a URL can be open programmatically, or via user action.

**Describe alternatives you've considered**
I thought that simply adding a URL in `Label` would cause iOS to auto-detect and make it clickable:

```
            self.outbox.add(toga.Label(
                f"Visit https://mysite.example.com",
                style=Pack(padding=(2,0)))
            )
```
but this didn't work.

**Additional context**

Being able to redirect/open a web page is pretty much table stakes for a mobile app these days, not being able to do so, is frustrating (even more so that `WebView` is not available for iOS)

**Comment by freakboy3742** [comment] 2021-03-30 02:21
Duplicate of #801.

**Closed by freakboy3742** 2021-03-30 02:21 UTC
Labels: duplicate, enhancement
