### ISSUE TITLE
Replace print statements with logging

### ISSUE THREAD

**Issue by Aareon** [beeware/toga#657] opened 2019-04-12 15:45 UTC
I've been looking through the `toga_win32` package and I've noticed that there are quite a few calls to `print`. I'd imagine tracking calls and logging errors might be a bit easier if we utilized `logging` here.

Does anyone have any issues with using `logging`, in addition to a unified log format, throughout the codebase?

**Comment by freakboy3742** [comment] 2019-04-13 11:19
The calls to `print` definitely need to be cleaned up; they'll be stray debug that has been left in.

I don't object to moving to logging as an API; the key will be ensuring good integration of system expectations of logging, and providing a clear interface for logging configuration. Each platform has a native-specific location where applicaitons *should* put their logs when they're wrapped up as user-space applications; that location may not be appropriate for an application being invoked directly from the command line as a Python tool.

**Comment by Aareon** [comment] 2019-04-13 20:40
I believe the last pary shouldn't be too difficult, but I am also unfamiliar with the iOS and Cocoas APIs as I don't have a Mac. Specifically for Windows, though, I see no problem in storing logs somewhere like `%appdata%/Toga/{app_name}`.

Most of the `logging` API would then be implemented in `toga.core` and stub functions placed in each of the various backends, respectively.

Off-topic, I was having some difficulty with using `python setup.py install` with Python 3.7 on Windows because of `toga-winforms` not being found. Are you familiar with whether or not `toga-winforms` is Py3.7 compatible?

**Comment by freakboy3742** [comment] 2019-04-17 07:07
That logging approach sounds about right for Windows (although the "Toga" part shouldn't be required - the fact that Python or Toga was used to write an app shouldn't leak into the user experience.

The issue is more one of configuration - where in the application lifecycle is the logging configuration stored, loaded, and so on - especially when it has to interact with native logging tools (e.g., on iOS and Android).

As for Py3.7 on Windows: The issue isn't toga-winforms per se; it's the python.net library. That library has been updated for Python 3.7 support, but they haven't published a wheel to PyPI. If you install python.net from source, it works - but you need to have a Windows compiler installed and configured for that to work.

**Comment by freakboy3742** [comment] 2020-04-25 13:41
Clarifying; the issue is that true "native" apps have native places to store logs. On macOS, that's the system log; it's probably a `/var` variant on Linux; and, as you note, there's `%appdata%` on Windows.

The feature request here is to build a generic Toga-level API for "logging" (possibly integrated into Python's own logging API) that will log to the "right" place.

**Closed** 2022-03-29 06:22 UTC
