### ISSUE TITLE
Windows: Background Color Not Applied to child Box

### ISSUE THREAD

**Issue by Vipul-Cariappa** [beeware/toga#988] opened 2020-07-27 10:36 UTC
## Expected Behavior

Background color should change, to the respective color set in Box widget.

## Current Behavior

Background color does not change.

## Steps to reproduce

<pre>
from toga import App, MainWindow, Label, Box
from toga.constants import BLUE, COLUMN
from toga.style import Pack

class Application(App):
    def startup(self):

        self.main_window = MainWindow(title=self.name)

        self.frame = Box(
            children=[
                Label("Some Text ...")
                ],
            style=Pack(
                direction=COLUMN,
                background_color=BLUE
            )
        )

        self.main_window.content = Box(children=[self.frame])

        self.main_window.content.refresh()
        self.main_window.show()

if __name__ == "__main__":
    app = Application("BugApp", "App")
    app.main_loop()

</pre>

## Your Environment

* Python Version 3.7

* Operating System and Version

  - [ ] Other - name:  - version:
  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - Windows 10:

* Toga Version
  - [x] 0.3.0.dev23

* Toga Target

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by Vipul-Cariappa** [comment] 2020-07-27 10:39
If we replace 
<pre>
self.main_window.content = Box(children=[self.frame])
</pre>
with this
<pre>
self.main_window.content = self.frame
</pre>
it works fine.

**Comment by mhsmith** [comment] 2022-11-14 09:44
Confirmed that this is still an issue on Windows with the current version of Toga. See https://github.com/beeware/toga/pull/1684#issuecomment-1313054915 for a more complete test case.

**Comment by freakboy3742** [comment] 2023-04-15 05:54
Closing as a duplicate of #767

**Closed by freakboy3742** 2023-04-15 05:54 UTC
Labels: bug, windows
