### ISSUE TITLE
Warning when using SplitContainer

### ISSUE THREAD

**Issue by stevemolloy** [beeware/toga#232] opened 2017-09-24 20:50 UTC
Using OSX, on the following setup:
```
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import toga
>>> print(toga.__version__)
0.3.0.dev1
```
Using toga.SplitContainer results in the following warning output in Pycharm:

```
/Users/stephenmolloy/PycharmProjects/toga_sandpit/venv3/bin/python /Users/stephenmolloy/PycharmProjects/toga_sandpit/make_a_window.py
2017-09-24 22:45:42.803 python[98013:2456501] Unable to simultaneously satisfy constraints:
(
    "<NSLayoutConstraint:0x7fcfe9485080 H:[NSSplitView:0x7fcfe957e110(>=300)]>",
    "<NSLayoutConstraint:0x7fcfe948d100 NSSplitView:0x7fcfe957e110.right == NSSplitView:0x7fcfe957e110.left + 126>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fcfe9485080 H:[NSSplitView:0x7fcfe957e110(>=300)]>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
STUB: If you want to handle opening documents, implement App.open_document(fileURL)
```

This output was created by the code in [this gist](https://gist.github.com/stevemolloy/1ff2d8d7f43aae7079f619db1e7bcb0c).

**Comment by freakboy3742** [comment] 2017-09-25 01:20
Thanks for the report, and the sample code. Looks like we've accidentally re-introduced a constraint issue in SplitContainer - I take it this same sample code *doesn't* produce this error on 0.2.15?

**Comment by stevemolloy** [comment] 2017-09-25 07:59
Correct.  No error is produced on 0.2.15  The output is as follows:
```
(venv_test) CI0011774:toga_sandpit stephenmolloy$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import toga
>>> print(toga.__version__)
0.2.15
>>> 
(venv_test) CI0011774:toga_sandpit stephenmolloy$ python make_a_window.py 
STUB: If you want to handle opening documents, implement App.open_document(fileURL)
```

**Comment by freakboy3742** [comment] 2017-09-28 14:23
Hrm. This is odd. I've just tried your sample code, and I *don't* get that constraint error. It's possible this might be a macOS version discrepancy - what version of macOS are you running?

**Comment by stevemolloy** [comment] 2017-09-28 14:27
<img width="698" alt="screen shot 2017-09-28 at 16 27 36" src="https://user-images.githubusercontent.com/17166614/30972048-d0779b2a-a469-11e7-8ccf-336ab207e94f.png">

**Comment by freakboy3742** [comment] 2017-09-28 14:51
Hrm. Ok. I'm on Sierra; I wouldn't have *thought* that would be the cause, but it's possible. I'll have to test on another box when I get a chance.

**Comment by Ocupe** [comment] 2017-09-30 17:08
I'm also on Sierra and get no warning.

**Comment by freakboy3742** [comment] 2017-10-01 02:18
@stevemolloy I've just pushed an update; a closer examination showed some changes from 0.2.15 that got accidentally dropped in the merge of the big refactor. Can you confirm if this update fixes the problem for you?

**Comment by stevemolloy** [comment] 2017-10-01 11:03
It didn't seem to make a difference.  Sorry.
Just to be clear on what I did.  I entirely removed the virtualenv (`rm -rf venv`), created a new one, and grabbed both toga and rubicon-objc from git.  I installed both of these using `pip install -e .`, and then tried the code again.

**Comment by freakboy3742** [comment] 2017-12-29 00:36
We've rolled out some major changes to Toga recently; can you confirm if you're still seeing this issue?

**Comment by freakboy3742** [comment] 2020-04-25 08:58
Closing on the basis that the underlying problem appears to have been addressed.

**Closed by freakboy3742** 2020-04-25 08:58 UTC
