### ISSUE TITLE
ImageView only works with square images

### ISSUE THREAD

**Issue by nikiosna** [beeware/toga#1140] opened 2020-11-17 15:23 UTC
I created a hello world app following this tutorial under Linux Mint 20: [https://docs.beeware.org/en/latest/tutorial/tutorial-0.html](https://docs.beeware.org/en/latest/tutorial/tutorial-0.html)
My python version is 3.8.5
When trying to add images some work and some not.

This code doesn't work:
`image_from_url = toga.Image("https://dummyimage.com/100x67/000/fff")
imageview_from_url = toga.ImageView(image=image_from_url, style=Pack(width=100, height=67))`

And this is working fine:
`image_from_url = toga.Image("https://dummyimage.com/100x100/000/fff")
imageview_from_url = toga.ImageView(image=image_from_url, style=Pack(width=100, height=100))`

The error I get is:

> (__main__.py:67130): GdkPixbuf-CRITICAL **: 16:12:00.644: gdk_pixbuf_scale_simple: assertion 'dest_height > 0' failed
>  ... TypeError: Argument 0 does not allow None as a value

**Comment by damascene** [comment] 2021-01-23 22:55
I'm having the same issue.

**Comment by freakboy3742** [comment] 2021-01-24 01:20
Thanks for the report. I've found the source of the problem; the issue is that the first time GTK tries to display the image, it allocates an available size of 1x1. Toga tries to preserve aspect ratio, which scales non-square images to have once of the dimensions with a size of 0 - which then breaks, because you can't have an image of size 0. A fix is incoming shortly.

**Closed** 2021-01-24 01:30 UTC
Labels: bug, linux
