### ISSUE TITLE
Crash on Android when adding background worker from a thread

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1539] opened 2022-08-01 00:22 UTC
Reported via https://github.com/beeware/toga/discussions/1538#discussioncomment-3286114

On Android, if you attempt to add an async background worker when in a thread, the worker won't start; in many cases, the app will crash.

**To Reproduce**

See the example program in the linked discussion thread; the key logic is to start a thread, and add a background worker when in that thread. The app will crash and/or the background worker will not run.

**Expected behavior**

It should be possible to add a background worker from any context.

**Environment:**
 - Operating System: Android
 - Python version: All
 - Software versions: 
   - Briefcase: 0.3.8
   - Toga: 0.3.0dev35

**Comment by freakboy3742** [comment] 2022-08-02 00:00
Further investigation by @spitskool42 has provided a related reproduction case; it appears the issue may not be the background worker per se, but the [visibility of the app object](https://github.com/beeware/toga/discussions/1538#discussioncomment-3295640).

**Comment by mhsmith** [comment] 2022-08-03 16:22
Minimal test case:
```
    def startup(self):
        from threading import Thread
        Thread(target=self.thread).start()

        main_box = toga.Box(style=Pack(direction="column"))
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def thread(self):
        print(self.app.paths.data)
```

The following error appears in the logcat (not shown by Briefcase because of excessive filtering):
```
2022-08-03 17:07:33.921 12329-12367/com.example.helloworld A/mple.helloworl: runtime.cc:677] JNI DETECTED ERROR IN APPLICATION: a thread (tid 12367 is making JNI calls without being attached
    runtime.cc:677]     in call to NewStringUTF
```

If a thread is created outside of Java, it must call the JNI function `AttachCurrentThread` before calling any other JNI functions. Rubicon doesn't do this, but Chaquopy does.

**Comment by mhsmith** [comment] 2022-08-03 16:56
Attempting to add a task from a background thread reveals another problem:
```python
    def startup(self):
        self.label = toga.Label("app started")

        main_box = toga.Box(style=Pack(direction="column"), children=[self.label])
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

        from threading import Thread
        Thread(target=self.thread).start()

    def thread(self):
        from time import sleep

        def set_text(text):
            def f(app):
                self.label.text = text
            return f

        self.app.add_background_task(set_text("thread started"))
        sleep(2)
        self.app.add_background_task(set_text("thread finished"))
```

```
W/python.stderr: Exception in thread 
W/python.stderr: Thread-1
W/python.stderr: :
W/python.stderr: Traceback (most recent call last):
W/python.stderr:   File "stdlib/threading.py", line 932, in _bootstrap_inner
W/python.stderr:   File "stdlib/threading.py", line 870, in run
W/python.stderr:   File "/data/data/com.example.helloworld/files/chaquopy/AssetFinder/app/helloworld/app.py", line 27, in thread
W/python.stderr:   File "/data/data/com.example.helloworld/files/chaquopy/AssetFinder/requirements/toga/app.py", line 561, in add_background_task
W/python.stderr:   File "/data/data/com.example.helloworld/files/chaquopy/AssetFinder/requirements/toga_android/app.py", line 199, in add_background_task
W/python.stderr:   File "stdlib/asyncio/base_events.py", line 723, in call_soon
W/python.stderr:   File "/data/data/com.example.helloworld/files/chaquopy/AssetFinder/app/rubicon/java/android_events.py", line 66, in _call_soon
W/python.stderr:   File "/data/data/com.example.helloworld/files/chaquopy/AssetFinder/app/rubicon/java/android_events.py", line 121, in enqueue_android_wakeup_for_delayed_tasks
W/python.stderr:   File "/data/data/com.example.helloworld/files/chaquopy/AssetFinder/app/rubicon/java/android_events.py", line 254, in call_later
W/python.stderr:   File "/data/data/com.example.helloworld/files/chaquopy/AssetFinder/app/rubicon/java/android_events.py", line 241, in handler
W/python.stderr:   File "class.pxi", line 135, in java.chaquopy.JavaClass.__call__
W/python.stderr:   File "class.pxi", line 209, in java.chaquopy.setup_object_class.JavaObject.__init__
W/python.stderr:   File "class.pxi", line 972, in java.chaquopy.JavaMultipleMethod.__get__.lambda3
W/python.stderr:   File "class.pxi", line 1010, in java.chaquopy.JavaMultipleMethod.__call__
W/python.stderr:   File "class.pxi", line 789, in java.chaquopy.JavaMethod.__call__
W/python.stderr:   File "class.pxi", line 837, in java.chaquopy.JavaMethod.call_constructor
W/python.stderr:   File "env.pxi", line 110, in java.chaquopy.CQPEnv.NewObjectA
W/python.stderr:   File "env.pxi", line 546, in java.chaquopy.CQPEnv.check_exception
W/python.stderr: java.lang
W/python.stderr: .
W/python.stderr: RuntimeException
W/python.stderr: : 
W/python.stderr: Can't create handler inside thread Thread[Thread-2,10,main] that has not called Looper.prepare()
W/python.stderr:     at android.os.Handler.<init>(Handler.java:227)
W/python.stderr:     at android.os.Handler.<init>(Handler.java:129)
```

This is caused by android_events.py delaying the creation of the handler until the first time `add_background_task` is called. But if this happens to be in a background thread, then the handler creation will fail, 

Fixed in the Chaquopy template PR by creating the handler on the main thread during startup.

**Comment by Spitskool42** [comment] 2022-08-03 18:09
wow great @mhsmith, good find. I have no idea how to debug this properly. do you use android studio when testing beeware/toga? 
Btw, heart about chaquopy now twice :P 
The next release will have the new Chaquopy android template? And the Android python support + rubicon-java will be discontinued?

**Comment by freakboy3742** [comment] 2022-08-04 02:00
@Spitskool42 We're currently investigating whether we're going to transition to using ChaquoPy as a base for Android support instead of Android-support+Rubicion-java; issues such as this one are making it very likely that this is going to be the path we will take. 

If we do go ahead with the transition, there's a few steps involved that still need to be planned, so it's difficult to say exactly the timeline involved; but my guess would be you'll see tangible changes in a month or two.

**Comment by mhsmith** [comment] 2022-08-04 08:11
> I have no idea how to debug this properly. do you use android studio when testing beeware/toga?

Yes, even if I'm not using Android Studio to open the actual BeeWare app, I find it useful for the [Logcat search function](https://developer.android.com/studio/debug/am-logcat).

**Closed** 2022-09-27 01:33 UTC
Labels: bug, up-for-grabs, android
