### ISSUE TITLE
Core tests failing on Windows (freeze at test_open_file_dialog)

### ISSUE THREAD

**Issue by gregcowell** [beeware/toga#1644] opened 2022-10-29 03:50 UTC
**Describe the bug**
I am running the core tests on Windows and they freeze at test_open_file_dialog:

test_validate_contains_zero_times (tests.test_validators.TestValidators) ... ok
test_validate_endswith (tests.test_validators.TestValidators) ... ok
test_validate_length_between (tests.test_validators.TestValidators) ... ok
test_validate_match_regex (tests.test_validators.TestValidators) ... ok
test_validate_maximum_length (tests.test_validators.TestValidators) ... ok
test_validate_minimum_length (tests.test_validators.TestValidators) ... ok
test_validate_not_contains (tests.test_validators.TestValidators) ... ok
test_validate_startswith (tests.test_validators.TestValidators) ... ok
test_add_same_widget_twice (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_add_two_widgets (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_add_widget (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_empty_registry (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_remove_widget (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_two_widgets_with_same_name (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_update_widgets (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_using_setitem_directly (tests.test_widget_registry.TestWidgetsRegistry) ... ok
test_close (tests.test_window.TestWindow) ... ok
test_confirm_dialog (tests.test_window.TestWindow) ... C:\Users\gregc\python\toga\toga\src\winforms\src\toga_winforms\dialogs.py:10: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
FAIL
test_error_dialog (tests.test_window.TestWindow) ... FAIL
test_full_screen_set (tests.test_window.TestWindow) ... ok
test_hide_raises_error_when_app_not_set (tests.test_window.TestWindow) ... ok
test_info_dialog (tests.test_window.TestWindow) ... C:\Program Files\Python310\lib\asyncio\base_events.py:685: ResourceWarning: unclosed event loop <WinformsProactorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
FAIL
test_on_close (tests.test_window.TestWindow) ... ok
test_on_close_at_create (tests.test_window.TestWindow) ... FAIL
test_open_file_dialog (tests.test_window.TestWindow) ...

**To Reproduce**
1. cd src/core
2. set TOGA_BACKEND=toga_dummy
3. python setup.py test

**Expected behavior**
All tests to succeed.

**Environment:**
 - Operating System: Windows 11
 - Python version: 3.10.5
 - Software versions:
   - Toga: 0.3.0.dev39

**Additional context**
Before running the tests:
1.  I synced my fork of Toga on GitHub.
2. Ran "git pull".
3. Reinstalled toga-core, toga-dummy and toga-winforms using "pip install -e src/core" etc.

**Comment by freakboy3742** [comment] 2022-10-30 00:00
I can't reproduce this locally, and CI has been [passing reliably on windows](https://github.com/beeware/toga/actions/runs/3341497998/jobs/5532800216) for a while, so this isn't a general problem - there's something specifically different about your setup.

The fact that the failing test is open_dialog suggests the problem is that the test is trying to actually display a dialog, which suggests the dummy backend isn't being picked up. If you have a clean virtual environment, with toga-core and toga-dummy, but *not* toga-winforms, does the test suite run at all?

**Comment by gregcowell** [comment] 2022-10-30 00:21
Yes, after running "pip uninstall toga-winforms" all tests pass. As you suspected, it seems like "set TOGA_BACKEND=toga_dummy" is not working. Various dialog boxes did run during the tests prior to uninstalling toga-winforms. I have run the tests successfully in the past so not sure what has changed apart from updating to Toga 0.3.0.dev39. 

I also created a brand new virtual environment with toga-winforms included and the core tests freeze again. "pip uninstall toga-winforms" fixes this also.

**Comment by freakboy3742** [comment] 2022-10-30 23:38
If you're seeing dialog boxes, that definitely means the test suite isn't running correctly. The Dummy backend should be internalising all the GUI calls. 

To confirm - when you say "0.3.0.dev39", do you mean that literal tagged release, or do you mean a recent toga checkout that is reporting that version number?

The next step for diagnosing this problem: set a breakpoint around [here](https://github.com/beeware/toga/blob/main/src/core/src/toga/platform.py#L68), and walk through the code to see why `TOGA_BACKEND` isn't being honoured on your machine.

**Comment by gregcowell** [comment] 2022-10-31 02:34
Thanks, a debugging session solved the mystery. 

I am using a recent Toga checkout that reports version "0.3.0.dev39".

The TOGA_BACKEND environment variable was not being set. I am using Windows Powershell not Command Prompt. Therefore I have to use:
`$env:TOGA_BACKEND="toga_dummy"`
instead of:
`set TOGA_BACKEND=toga_dummy`

Windows Powershell was silently failing to set the environment variable when I used the latter command. I am not sure why I have not run into this problem previously. Perhaps I was using Command Prompt last time I ran the tests.

**Comment by freakboy3742** [comment] 2022-10-31 06:27
Ah - that would explain it. On that basis, I'm going to close this ticket. If you think there's something else lurking here that needs attention, let us know and I'm happy to re-open.

As for why you weren't seeing this previously: the change that required the TOGA_BACKEND environment variable only landed mid last week. Prior to that, the dummy backend was implied when running the core tests.

**Closed by freakboy3742** 2022-10-31 06:27 UTC
Labels: bug, more-details, windows
