### ISSUE TITLE
window.open_file_dialog(...,multiselect=True) returns System.String[]

### ISSUE THREAD

**Issue by EntPyle** [beeware/toga#1220] opened 2021-03-10 16:29 UTC
**Describe the bug**
With multiselect on, the open_file_dialog() function returns a System.String[] parameter for both single and multi-selections. The user has to pass the return value to an iterable builder (e.g. list()) in order to get a list of absolute paths.

**To Reproduce**
1. Run this modified 'Hello World' example to open a file dialog.
```
  import toga
  
  
  def button_handler(widget):
      print("hello")
      try:
          # selected_file = list(widget.window.open_file_dialog('Select Files', multiselect=True))
          selected_file = widget.window.open_file_dialog('Select Files', multiselect=True)
      except ValueError:
          print('No file selected')
      else:
          print(selected_file)
  
  
  def build(app):
      box = toga.Box()
  
      button = toga.Button('Open File Dialog', on_press=button_handler)
      button.style.padding = 50
      button.style.flex = 2
      box.add(button)
  
      return box
  
  
  def main():
      return toga.App('Testing App', 'org.beeware.helloworld', startup=build)
  
  
  if __name__ == '__main__':
      main().main_loop()
```
2. Click on the "Open File Dialog" Button.
3. Select and open a file.
4. The output is printed to screen.
5. Comment out line 8 and line 7 to see corrected behavior

**Expected behavior**
According to the docs, this function already returns a list when multiselect is on. Should be simple enough to add list() into the function to rectify this. 

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.7.6
 - Software versions:
   - Briefcase: I don't have this (just installed today) so that might be a problem... 
   - Toga: 0.3.0.dev26
   - ...

**Additional context**
No other comments. I'm pretty excited about this effort and am going to try and contribute myself. I am mainly work on Windows so I can help close that gap.

**Comment by shape-warrior-t** [comment] 2022-07-23 03:09
This issue seems to be no longer relevant.

The interface of `open_file_dialog` seems to have changed so that with multiselect it now returns an awaitable object that in turn returns a list of paths. On Windows, all functionality seems to work as expected.

The code snippet provided no longer functions as intended. After fixing it by defining `button_handler` as async and awaiting both `open_file_dialog` calls, there is no difference, output-wise, between calling and not calling `list` on the awaited result. Both times, the type returned is a `list`.

**Comment by freakboy3742** [comment] 2022-07-24 23:43
@shape-warrior-t Looks like you're correct - this was fixed inadvertently as part of the recent async dialog changes. Thanks for the investigation work!

**Closed by freakboy3742** 2022-07-24 23:43 UTC
Labels: bug, up-for-grabs, windows

**Comment by kamal-zaitar** [comment] 2023-06-21 11:14
#this will print list of paths
async def button_handler(widget):

      try:

          selected_file = await widget.window.open_file_dialog('Select Files', multiselect=True)

      except ValueError:

          print('No file selected')

      else:

          print(selected_file)
