### ISSUE TITLE
Tutorial 3 not working windows

### ISSUE THREAD

**Issue by outforpublic** [beeware/toga#770] opened 2019-12-31 15:41 UTC
## Expected Behavior

https://toga.readthedocs.io/en/latest/tutorial/tutorial-3.html

## Current Behavior

nothing, then:
```
Traceback (most recent call last):
  File "C:\Users\tract\AppData\Local\Temp\browser.py", line 1, in <module>
    import toga, logging
  File "C:\Program Files\Python37\lib\site-packages\toga\__init__.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "C:\Program Files\Python37\lib\site-packages\toga\app.py", line 6, in <module>
    from toga.command import CommandSet
  File "C:\Program Files\Python37\lib\site-packages\toga\command.py", line 1, in <module>
    from toga.handlers import wrapped_handler
  File "C:\Program Files\Python37\lib\site-packages\toga\handlers.py", line 1, in <module>
    import asyncio
  File "C:\Program Files\Python37\lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 18, in <module>
    import concurrent.futures
  File "C:\Program Files\Python37\lib\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Program Files\Python37\lib\concurrent\futures\_base.py", line 42, in <module>
    LOGGER = logging.getLogger("concurrent.futures")
AttributeError: module 'logging' has no attribute 'getLogger'
```

## Steps to reproduce

1. Run the Tutorial 3 code from the readthedocs on windows

2.

3.

## Your Environment

* Python Version (list the specific version number)
`Python 3.7.5`
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: 10.0.18362 Build 18362 x64
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
`0.3.0.dev16`
* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment] 2020-01-01 00:34
Ok - so... there's a lot of confusion here.

Firstly, the report title says "Tutorial 4 not working" but then you reference Tutorial 3. 

Tutorial 4 *won't* work on Windows - but that's because we don't have a Canvas widget for Windows (yet).

Assuming the problem is actually with Tutorial 3 (which is what most of the rest of your error report suggests) - I can't reproduce the error you're seeeing.

The error you've reported suggests something is *very* wrong with your Python install - the stack trace indicates that the problem is occurring inside the `concurrent` library, because ``logging.getLogger`` doesn't exist. I don't know what has happened to your Python install, but if there's no getLogger method in the logging module, something is *badly* wrong with your Python install.

The stack trace also indicates that you're *not* running the code "as provided". The very first line of the stack trace indicates you've got the line `import toga, logging` in your code, which isn't what the tutorial directs you to run. So, you've apparently made *some* changes to your code beyond what is in the tutorial. It's difficult to diagnose the problem unless you tell us what those changes are.

My guess is that you've got a `logging.py` file in the same directory that you're storing `browser.py`, or that you've got your own `logging` module somewhere on your PYTHONPATH. This might be happening if you're *not* using a virtual environment (which the tutorial suggests at an earlier step).

**Comment by freakboy3742** [comment] 2020-04-25 15:15
Closing due to a lack of follow up, and an inability to reproduce the bug as reported.

**Closed by freakboy3742** 2020-04-25 15:15 UTC
