### ISSUE TITLE
Seg fault while selecting different rows in a table on macOS

### ISSUE THREAD

**Issue by rmartin16** [beeware/toga#2002] opened 2023-06-20 16:33 UTC
### Describe the bug

I noticed the `table` example would eventually crash on macOS with a seg fault while I would click different rows in the table. This would reliably happen in less than 30s. Of note, my macOS environment is virtualized...so, maybe this doesn't happen on Apple hardware.

[macOS_error.log](https://github.com/beeware/toga/files/11803405/macOS_error.log)

### Steps to reproduce

`briefcase run` in the `table` example and select one row after another in the table

### Expected behavior

No seg fault

### Environment

- Operating System: Monterey
- Python version: 3.11.4
- Software versions:
  - Briefcase: `0.3.15.dev361+g02f412be.d20230620`
  - Toga: `toga_cocoa-0.3.2.dev388+g68ac31aa`

### Logs

[briefcase.2023_06_20-12_31_47.run.log](https://github.com/beeware/toga/files/11803378/briefcase.2023_06_20-12_31_47.run.log)

**Comment by freakboy3742** [comment] 2023-06-20 23:18
Thanks... I hate it... :-)

I haven't been able to reproduce this myself. To clarify - I can see this is the Table demo, running on a (virtualised) x86_64 Mac; can you clarify the sequence of events that causes the crash? Is it literally "click on row 1, click on row 2, rinse and repeat" for 30 seconds? Is this on the left or right version of the table?

**Comment by rmartin16** [comment] 2023-06-20 23:32
> Thanks... I hate it... :-)

🙃 

> Is it literally "click on row 1, click on row 2, rinse and repeat" for 30 seconds?

Yep; this works....any usually doesn't take near 30s.

> Is this on the left or right version of the table?

Either one....or just alternating clicks between them.

I'd make a video....but it's really just any sequence of clicking on the table leads to a crash.

**Comment by freakboy3742** [comment] 2023-06-26 08:06
@rmartin16 Can I ask you to take #2011 for a spin? I still haven’t been able to reproduce this (including writing an automated test case that clicked thousands of times) - but I’ve also made a couple of cleanups to the Cocoa Table implementation that might have inadvertently cleaned up some memory issues.

**Comment by rmartin16** [comment] 2023-06-26 14:34
Unfortunately, it's the same behavior with #2011. In fact, upon rebuilding and opening the `table` example, it crashed on the very first click in to the table.

**Comment by freakboy3742** [comment] 2023-06-26 22:53
Hmph... well that's annoying... I can't reproduce this on either x86 or M1 Macs - definitely not as explosively as the first selection.

**Comment by freakboy3742** [comment] 2023-06-27 22:39
@rmartin16 Thinking outside the box here - is there any possibility what you're seeing is actually #1156? I'm able to reliably cause *that* error, but simple clicking does nothing. I'm wondering if there's some quirk of your mouse setup (or your wrist action? ;-) ) that is triggering the start of a drag action. 

One possible check for this - does `briefcase run --test` work for you on the testbed app? 

If it does - If you add the following test can to `testbed/tests/widgets/test_table.py`, does it pass?
```
import random


async def test_click(widget, probe, source, on_select_handler):
    row = 1
    for i in range(0, 100):
        row = (row + 3) % 14
        await probe.select_row(row)
        await probe.redraw(f"{i}: row {row} is selected")
        on_select_handler.assert_called_once_with(widget)
        on_select_handler.reset_mock()
```

**Comment by rmartin16** [comment] 2023-06-27 23:18
> @rmartin16 Thinking outside the box here - is there any possibility what you're seeing is actually #1156? I'm able to reliably cause _that_ error, but simple clicking does nothing. I'm wondering if there's some quirk of your mouse setup (or your wrist action? ;-) ) that is triggering the start of a drag action.

ahhh....I didn't know there was an existing issue for seg fault on "dragging" a row. This is likely the same issue then because I wasn't being careful not to move the mouse while I was clicking. This is also likely exacerbated by the fact there's no actual virtualization support for macOS; so, the mouse movement is choppy and delayed.

> 
> One possible check for this - does `briefcase run --test` work for you on the testbed app?

This passes.

> 
> If it does - If you add the following test case to `testbed/tests/widgets/test_table.py`, does it pass?
> 
> ```
> import random
> 
> 
> async def test_click(widget, probe, source, on_select_handler):
>     row = 1
>     for i in range(0, 100):
>         row = (row + 3) % 14
>         await probe.select_row(row)
>         await probe.redraw(f"{i}: row {row} is selected")
>         on_select_handler.assert_called_once_with(widget)
>         on_select_handler.reset_mock()
> ```

This test fails....although, because of a mock not being called.

(I'll add the full error from the VM....since there's no copy/paste out of it...)

**Comment by freakboy3742** [comment] 2023-06-27 23:22
That mode of test failure isn't entirely unexpected - if it selects the same row twice (or there's a long lag in event processing), it could fail due to a mock not being triggered. If the failure is due to the mock, not due to a segfault, I think we've narrowed down the problem here. On that basis, I think I'll close this ticket in favor of #1156; however, I'm no closer to having any idea how to *fix* that one...

**Closed by freakboy3742** 2023-06-27 23:22 UTC
Labels: bug, macOS
