### ISSUE TITLE
GTK+ SplitContainer & ScrollContainer Not Impletemented

### ISSUE THREAD

**Issue by Agwebberley** [beeware/toga#1586] opened 2022-09-06 22:15 UTC
**Describe the bug**
GTK+ says that it has not implemented SplitContainer or ScrollContainer even though the documentation says that it does

**To Reproduce**
1. Have a program that implements SplitContainer or ScrollContainer
2. Run briefcase dev on GTK+
3. There is no error but a Debug message shows 
"DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.native.set_wmclass(app.interface.name, app.interface.name)
[GTK+] Not implemented: SplitContainer.set_direction()
[GTK+] Not implemented: ScrollContainer.set_on_scroll()"

**Expected behavior**
A Scroll Container and a Split Container to show up.

**Environment:**
 - Operating System: Pop OS 21.04
 - Python version: 3.10.4
 - Software versions:
   - Briefcase: 0.3.9
   - Toga: 0.3.0.dev36

**Comment by freakboy3742** [comment] 2022-09-06 22:27
I don't know what has given you the impression that they don't exist, because there is both a [SplitContainer](https://github.com/beeware/toga/blob/main/src/gtk/toga_gtk/widgets/splitcontainer.py) and [ScrollContainer](https://github.com/beeware/toga/blob/main/src/gtk/toga_gtk/widgets/scrollcontainer.py) widget implemented on GTK, and [tutorial 2](https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html) contains an example of both of these widgets working. 

The messages you describe are *warnings* telling you that specific *methods* on those two widgets haven't been implented - but the widgets themselves definitely exist and work.

As you haven't provided a specific example that reproduces the problem, we can't clarify if this is an error of usage. Closing on that basis.

**Closed by freakboy3742** 2022-09-06 22:27 UTC
Labels: bug
