### ISSUE TITLE
Selection list stays open after item selected on iOS

### ISSUE THREAD

**Issue by athosflo** [beeware/toga#1223] opened 2021-03-14 12:32 UTC
I have made a program on MacOS, which uses toga.selection with a list of items to select from. On the MacOS, when I click on the selection, a list opens, I select the item, the list closes and the selected item is displayed.

However on iOS, the list stays open after the item has been selected. Any idea how to close the selection list after having selected the item ?

Thanks

**Comment by freakboy3742** [comment] 2022-03-29 07:35
It's very hard to answer without specific code; however, I suspect this is due to a bug in iOS.

However, it's difficult to say without a reproduction case. Closing on that basis; if you can provide a reproduction case, we can re-open.

**Closed by freakboy3742** 2022-03-29 07:35 UTC
