### ISSUE TITLE
Questions about editing the code

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1043] opened 2020-09-11 00:21 UTC
At first, I would like to support you with sympathy and thanks for this great project.

This isn't an issue, but I wonder how to deal with some spelling errors or code formatting errors that may be in a file that I am not modifying, do I modify this error and present it in the PR which may be a PR to add a new `Widget`. For example: I found the following typo and in fact I will not modify this file I was just trying to read it. I'm wondering because I'm afraid this might be a annoying for someone who trying to track my code modifications to review them.
![Screenshot at 2020-09-11 02-12-00](https://user-images.githubusercontent.com/50509521/92829635-f43c8280-f3c3-11ea-81a5-dcd5eb91843b.png)

Also, I wonder about the possibility of using [black](https://pypi.org/project/black/) for automatic formatting, I found it very compatible with the thing used in the code, except for some lines, which offers good look alternatives, I wonder because I think it is better for the developer to focus on the code itself and let the formatting happen automatically. Following is an example:
Before `black` formatting:
![before](https://user-images.githubusercontent.com/50509521/92830176-8ba1d580-f3c4-11ea-943b-8021b02fae90.png)
After `black` automatic formatting:
![after](https://user-images.githubusercontent.com/50509521/92830204-92304d00-f3c4-11ea-933f-c4c75878572c.png)

**Comment by freakboy3742** [comment] 2020-09-11 01:52
Hi @MuhammadMouradG! Feel free to to submit a pull request for any annoying typos you see - either as a standalone "fix typos" pull request, or integrated into another patch if you're submitting a fix/improvement and want to "clean up the campground" to leave it nicer than it was before.

As for adopting black - that's definitely on our radar, as I definitely agree with the goals of black as a problem. The problem is that there's a couple of bugs in Black that are currently show-stoppers for me, as they actively degrade readability of code. I *think* one of those bugs may have been addressed in the most recent release - but I need to find some time to investigate further.

Suffice to say that adding black is something we *want* to do - but the tool needs to be in service of the code, not the other way around.

**Comment by MuhammadMouradG** [comment] 2020-09-11 03:00
@freakboy3742 thanks for your prompt response.

OK, I got the point.

Finally, are you using alternative to `black`, or where I can find the rules that you are following for formatting.

**Comment by freakboy3742** [comment] 2020-09-11 03:20
We're currently using `flake8` to enforce style rules; the flake8 configuration is in the `config.cfg` file in the repo.

(Closing this ticket since your original question has been answered; if you need follow up answers, feel free to ask them here, or on another question)

**Closed by freakboy3742** 2020-09-11 03:20 UTC
Labels: question

**Comment by saroad2** [comment] 2020-09-11 07:24
> As for adopting black - that's definitely on our radar, as I definitely agree with the goals of black as a problem. The problem is that there's a couple of bugs in Black that are currently show-stoppers for me, as they actively degrade readability of code. I _think_ one of those bugs may have been addressed in the most recent release - but I need to find some time to investigate further.

Many bugs in *black* have been fixed in the latest release. It's worth your time :)
I run *black* all over my code in *Eddington*, and I'm not sorry even for a moment.
