### ISSUE TITLE
reactive ui development like react or vue

### ISSUE THREAD

**Issue by keinagae** [beeware/toga#1583] opened 2022-09-05 15:33 UTC
Are there any plans to make toga are reactive framework like react or vue?

**Comment by mhsmith** [comment] 2022-09-05 17:52
Can you explain what you mean by "reactive", and give an example of how Toga doesn't currently meet the definition?

**Comment by freakboy3742** [comment] 2022-09-05 22:53
If I'm understanding correctly, this is a reference to the "pipeline of transformations" approach that is used by frameworks like React and Vue. ([Here's an overview of what "reactivity" means in the context of Vue](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#declaring-methods); the approach is consistent with React's approach).

If this is what you were intending - the short answer is No, there aren't any plans to make Toga "Reactive". The reactive approach was developed primarily because of the needs of widget rendering on a web canvas. While it *can* be implemented with native widgets, in my experience the benefits are less significant, as the API being used is a rich widget API managed by the operating system, not a set of drawing primitives that need to be reproduced on a HTML webview.

The elements of reactive GUI toolkits that *are* beneficial aren't really specific to Reactive toolkits. 

Although Toga is currently API based, adding a declarative/markup based API for laying out widgets would be relatively straightforward. We might add one at some point, but we don't have any immediate plans to do so.

Separation of data and widget state is another useful property of Reactive APIs - but it's also a property that is common to other GUI API approaches, such as MVC. Toga has a data separation API (Sources) which we expect to expand on over time.

I'm going to close this ticket on the basis that it doesn't have a specific API proposal; if you want to make a specific proposal, I suggest you open a discussion topic, rather than an issue.

**Closed by freakboy3742** 2022-09-05 22:53 UTC
Labels: enhancement
