### ISSUE TITLE
Support Qt as a native toolkit

### ISSUE THREAD

**Issue by probonopd** [beeware/toga#1341] opened 2021-10-10 14:37 UTC
**Describe the bug**

The project claims to use "native" widgets, but on Linux this is not true for desktops that are built on Qt rather than Gtk.
Not every system has Gtk installed.

**To Reproduce**

Start with the Tutorial, see the sentence

>If you’re on Linux, you need to have GTK+ 3.4 or later. This is the version that ships starting with Ubuntu 12.04 and Fedora 17.

**Expected behavior**

Gtk and Qt should both be treated as "native" for Linux, no preference should be given to one of them.

**Additional context**

https://github.com/beeware/toga/tree/master/nursery/qt

says

> THIS IS A PLACEHOLDER PROJECT

**Comment by freakboy3742** [comment] 2021-10-10 22:25
Duplicate of #1142. 

We'd absolutely love to support Qt as well; that's why there's a placeholder entry in the nursery. However, we're a volunteer project with limited resources, so we've picked one for now.

If anyone knows Qt/KDE APIs (or wants to learn them), and wants to work on this project, I'm happy to provide pointers or details on how to tackle the project.

**Closed by freakboy3742** 2021-10-10 22:25 UTC
Labels: bug, duplicate
