### ISSUE TITLE
Error AttributeError: 'NoneType' object has no attribute '_impl'

### ISSUE THREAD

**Issue by dillonhaughton** [beeware/toga#1473] opened 2022-04-27 13:33 UTC
Application runs on macOS but shows this error when running on iOS.
error looks like it is in reference to a scroll container

**Comment by freakboy3742** [comment] 2022-04-28 07:29
Transferred from Briefcase because the issue is with the Toga GUI framework, not the Briefcase packaging tools.

It's very difficult to diagnose a bug when all we have to go on in "When I replaced a scroll container with a box".

Could you provide a complete reproduction case for this bug?

**Comment by dillonhaughton** [comment] 2022-05-02 02:44
def startup(self):
	#-------------------------------------------------------------------------------------------
	#                                   Home Screen Section
	#-------------------------------------------------------------------------------------------
		
		
		self.new_class = toga.Button('New Material', on_press=self.new_material_window)
		
		# Create New Material Section
		self.class_bar_items = []
		# Going Back to Old Format Start Here
		current_classes = os.listdir(data_path)
		if '.DS_Store' in current_classes: current_classes.remove('.DS_Store')
		
		self.class_bar_items += current_classes
		self.class_bar   = toga.Selection(items=self.class_bar_items, on_select=self.class_bar_shift)

		# Stops working here on iOS
		#-----------------------------------------------------------------------------
		# Subject Display
		
		
		subject_1 = os.listdir(os.path.join(data_path, current_classes[0]))
		#print(subject_1)
		
		if '.DS_Store' in subject_1: subject_1.remove('.DS_Store')

		if len(subject_1) > 0:
			subject_data = []
			for row in subject_1:
				#gen_frame = pd.read_csv(os.path.join(data_path, self.class_bar.value, row, 'general_data.csv'), header=0, index_col=0)
				gen_frame = list(csv.reader(open(os.path.join(data_path, self.class_bar.value, row, 'general_data.csv'))))
				#print(gen_frame)
				score = gen_frame[-1][3]
				L_F   = gen_frame[-1][6]
			
				days_since = datetime.datetime.now() - datetime.datetime.fromisoformat(gen_frame[-1][2])
				days_since = days_since.days

				chunk = {'icon':'', 'title':row, 'subtitle':'testing'}
				subject_data.append(chunk)
				print(subject_data)
				
		else:
		
			subject_data = []
		
		self.selection = toga.DetailedList(data = subject_data, style=Pack(height = 200))
			
		self.add_button = toga.Button('Manage Cards', on_press=self.manage_cards_window)
		self.review_card= toga.Button('Test', on_press=self.test_window)
		#self.scroll_box = toga.Box(children = [self.add_button, self.review_card], style=Pack())

		# Not sure why this doesnt work
		# This seems to be causing some issues, but when taken out the app crashes all together
		#self.scroller     = toga.ScrollContainer(style=Pack(flex=1, padding=20), horizontal=False, vertical=False)
		#self.scroller.content = self.scroll_box

		self.row1 = toga.Box(children=[self.new_class, self.class_bar, self.selection, self.add_button, self.review_card], style=Pack(direction=COLUMN))
		
		
		self.main_window = toga.MainWindow(title=self.formal_name)


		self.main_window.content = self.row1
		self.main_window.show()

Here is my code for my main window. Running it on Mac it will run fine but in iOS it will stall with the above error Python runtime error: Invalid parameter not satisfying: traitCollection != nil. 

If I take out the data in the DetailedList it will run but it will not run if I attempt to put anything in the Detailed List.

**Comment by dillonhaughton** [comment] 2022-05-14 21:24
I tried the example of the Detailed List and it still returns this error. Has anyone tried the DetailedList example on iOS and gotten it to work?

**Comment by freakboy3742** [comment] 2022-05-15 02:14
@dillonhaughton It *did* work at some point in the past; but it's likely that it's suffered some bitrot.

**Comment by dillonhaughton** [comment] 2022-05-15 15:47
At this point ill move on with my iOS project without a detailed list the selection widget should work fine enough. But if someone has the time to send me a detailed list example that working on iOS I would appreciate it.

**Comment by rbryx** [comment] 2022-08-12 07:22
Have you been able to reproduce the bug with my example?

**Comment by mhsmith** [comment] 2022-08-12 07:45
Can you provide the following information?
* The full stack trace.
* The Toga version numbers from your pyproject.toml file.

**Comment by rbryx** [comment] 2022-08-12 10:29
I made a fresh new briefcase and just create a ScrollContainer instance:
`"""
Check scroll container availability for iOS
"""
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class TogaScrollBug(toga.App):

    def startup(self):
        """
        Construct and show the Toga application.

        Usually, you would add your application to a main content box.
        We then create a main window (with a name matching the app), and
        show the main window.
        """
        main_box = toga.Box()
        scroll = toga.ScrollContainer()

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return TogaScrollBug()
`

**Comment by rbryx** [comment] 2022-08-12 10:30
here is the trace:

[togascrollbug] Following simulator log output (type CTRL-C to stop log)...
===========================================================================
Error from getpwuid_r: 0 (Undefined error: 0)
Filtering the log data using "senderImagePath ENDSWITH "/Toga Scroll Bug""
Timestamp               Ty Process[PID:TID]
2022-08-12 12:24:52.174 Df Toga Scroll Bug[3001:1dd8b] Configuring isolated 
Python...
2022-08-12 12:24:52.178 Df Toga Scroll Bug[3001:1dd8b] PythonHome: 
/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-15636
43C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075/
Toga Scroll Bug.app/Library/Python
2022-08-12 12:24:52.312 Df Toga Scroll Bug[3001:1dd8b] PYTHONPATH:
2022-08-12 12:24:52.312 Df Toga Scroll Bug[3001:1dd8b] - 
/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-15636
43C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075/
Toga Scroll Bug.app/Library/Python/lib/python3.9
2022-08-12 12:24:52.313 Df Toga Scroll Bug[3001:1dd8b] - 
/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-15636
43C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075/
Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages
2022-08-12 12:24:52.313 Df Toga Scroll Bug[3001:1dd8b] - 
/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-15636
43C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075/
Toga Scroll Bug.app/Library/Application Support/com.brx.togascrollbug/app
2022-08-12 12:24:52.314 Df Toga Scroll Bug[3001:1dd8b] Configure argc/argv...
2022-08-12 12:24:52.314 Df Toga Scroll Bug[3001:1dd8b] Initializing Python 
runtime...
2022-08-12 12:24:52.768 Df Toga Scroll Bug[3001:1dd8b] Installing Python NSLog 
handler...
2022-08-12 12:24:52.798 Df Toga Scroll Bug[3001:1dd8b] Running app module: 
togascrollbug
2022-08-12 12:24:54.971 Df Toga Scroll Bug[3001:1dd8b] App finished launching.
2022-08-12 12:24:55.066 Df Toga Scroll Bug[3001:1dd8b] Exception ignored on 
calling ctypes callback function: <rubicon.objc.api.objc_method object at 
0x122b49f10>
2022-08-12 12:24:55.067 Df Toga Scroll Bug[3001:1dd8b] Traceback (most recent 
call last):
2022-08-12 12:24:55.068 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/rubicon/objc/api.py", line 275, in 
__call__
2022-08-12 12:24:55.070 Df Toga Scroll Bug[3001:1dd8b]     result = 
self.py_method(py_self, *args)
2022-08-12 12:24:55.071 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga_iOS/app.py", line 40, in 
application_didFinishLaunchingWithOptions_
2022-08-12 12:24:55.074 Df Toga Scroll Bug[3001:1dd8b]     App.app.create()
2022-08-12 12:24:55.076 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga_iOS/app.py", line 99, in create
2022-08-12 12:24:55.078 Df Toga Scroll Bug[3001:1dd8b]     
self.interface.startup()
2022-08-12 12:24:55.079 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app/togascrollbug/app.py", line 20, in startup
2022-08-12 12:24:55.081 Df Toga Scroll Bug[3001:1dd8b]     scroll = 
toga.ScrollContainer()
2022-08-12 12:24:55.082 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga/widgets/scrollcontainer.py", 
line 29, in __init__
2022-08-12 12:24:55.083 Df Toga Scroll Bug[3001:1dd8b]     self._impl = 
self.factory.ScrollContainer(interface=self)
2022-08-12 12:24:55.084 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga_iOS/widgets/base.py", line 13, 
in __init__
2022-08-12 12:24:55.085 Df Toga Scroll Bug[3001:1dd8b]     
self.interface.style.reapply()
2022-08-12 12:24:55.086 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/travertino/declaration.py", line 88, 
in reapply
2022-08-12 12:24:55.087 Df Toga Scroll Bug[3001:1dd8b]     self.apply(style, 
getattr(self, style))
2022-08-12 12:24:55.087 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga/style/pack.py", line 104, in 
apply
2022-08-12 12:24:55.088 Df Toga Scroll Bug[3001:1dd8b]     
self._applicator.set_font(
2022-08-12 12:24:55.089 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga/style/applicator.py", line 25, 
in set_font
2022-08-12 12:24:55.090 Df Toga Scroll Bug[3001:1dd8b]     
self.widget._impl.rehint()
2022-08-12 12:24:55.090 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga_iOS/widgets/scrollcontainer.py",
line 133, in rehint
2022-08-12 12:24:55.091 Df Toga Scroll Bug[3001:1dd8b]     
self.update_content_size()
2022-08-12 12:24:55.092 Df Toga Scroll Bug[3001:1dd8b]   File 
"/Users/brx/Library/Developer/CoreSimulator/Devices/1185E41E-92F8-4538-A922-1563
643C1625/data/Containers/Bundle/Application/17A80A2E-C64A-467E-9877-9E43A0823075
/Toga Scroll Bug.app/Library/Application 
Support/com.brx.togascrollbug/app_packages/toga_iOS/widgets/scrollcontainer.py",
line 20, in update_content_size
2022-08-12 12:24:55.093 Df Toga Scroll Bug[3001:1dd8b]     scrollable_content = 
self.interface.content._impl
2022-08-12 12:24:55.093 Df Toga Scroll Bug[3001:1dd8b] AttributeError: 
'NoneType' object has no attribute '_impl'
2022-08-12 12:24:55.164 Df Toga Scroll Bug[3001:1dd8b] App became active.

**Comment by rbryx** [comment] 2022-08-12 10:39
toml says >=0.3.0.dev34 but I saw briefcase installed >=0.3.0.dev35:

[tool.briefcase]
project_name = "Toga Scroll Bug"
bundle = "com.brx"
version = "0.0.1"
url = "https://brx.com/togascrollbug"
license = "BSD license"
author = 'Fabrizio Grassi'
author_email = "rbryx@tiscali.it"

[tool.briefcase.app.togascrollbug]
formal_name = "Toga Scroll Bug"
description = "Check scroll container availability for iOS"
icon = "src/togascrollbug/resources/togascrollbug"
sources = ['src/togascrollbug']
requires = [
]


[tool.briefcase.app.togascrollbug.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.togascrollbug.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.togascrollbug.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.togascrollbug.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.togascrollbug.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.togascrollbug.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.togascrollbug.android]
requires = [
    'toga-android>=0.3.0.dev34'
]

**Comment by mhsmith** [comment] 2022-08-12 15:27
Thanks: I'm not set up for iOS development myself, but I'm sure @freakboy3742 will get back to you within the next few days.

**Comment by freakboy3742** [comment] 2022-08-15 09:11
I was able to narrow down the problem for the ScrollContainer case; #1557 contains a fix. 

The original reported DetailedList problem is slightly different; the "traitCollection != nil" error looks like an error at the Rubicon layer, suggesting something has changed slightly in the iOS declaration of UITableViewController. I'll need to dig deeper to work out the problem here.

**Closed** 2023-09-09 23:56 UTC
Labels: bug, iOS, awaiting details
