### ISSUE TITLE
Memory leaks in Windows

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1108] opened 2020-10-20 07:15 UTC
**Describe the bug**
Unfortunately, it seems like there are memory leaks issues in the Windows implementation of toga

**To Reproduce**
1. install memory profiler, briefcase and matplotlib using `pip install memory_profiler briefcase matplotlib`
2. Go to the Box example directory (or any other example for that matter)
3. Run `mprof run --include-children briefcase dev`
4. Click some buttons and wait for a few seconds
5. Exit the program
6. run `mprof plot` and see the memory leak

![memory_leak](https://user-images.githubusercontent.com/19425795/96552884-11b31500-12bd-11eb-8c31-78aaeab5ca88.png)

**Environment:**
 - Operating System: Windows 10
 - Python version: python 3.8
 - Software versions:
   - Briefcase: latest
   - Toga: latest

**Comment by freakboy3742** [comment] 2021-04-05 02:29
Reopened this after merging #1243.

There's clearly a memory leak going on here, but it appears to be related to *every* event callback, not just the proactor. Even after you apply the patch from #1109, you can see a small leak every time you click on a button. The proactor is effectively implementing "click a button every 5ms", which is why the leak is more obvious when the proactor is running, but the problem doesn't appear to be inherently because of leaks in the proactor.

I've been able to reproduce this entirely in pure Python.net; I've opened pythonnet/pythonnet#1434 to see if they have any input on the problem.

**Comment by saroad2** [comment] 2021-05-15 10:29
Hey, is there any progress with this issue?
Are we sure this is a bug in Pythonnet and not Toga-related?

**Comment by freakboy3742** [comment] 2021-05-15 11:31
I haven't had a chance to look any deeper. I can't 100% guarantee it's Pythonnet, but from my most recent testing, it certainly looked like it was.

**Comment by t-arn** [comment] 2022-05-11 22:54
Today, I discovered a massive memory leak in my calculator app (Python 3.8, Toga) when running on Windows 10.
The memory consumption starts at about 48 MB and then increases by 14 MB per minute while the app is doing absolutely nothing except waiting for user input! I tried to start the app with python.exe instead of pythonw.exe but the memory leak remains.

@freakboy3742 says that this is the most aggressive memory leak he's seen so far. So, what is so special about this app? And why don't I have this problem with my REST webservice app (Python 3.9, CLI)?

My gut feeling is this: The problem is in the main loop of the UI, more specifically in the UI event handlers. The logic behind this? A calculator has **a lot** of buttons (about 40 in my app) which means **a lot** of on_click handlers which sums up to a **big** memory leak. The webservice app has 0 buttons, 0 UI handlers and therefore 0 memory leak.

To confirm my feeling, it should be enough to create a simple 1 window app with about 50 buttons and set the on_click handler for each button. Probably, it can be the same function for all buttons. And then, start the app and observe the memory consumption in the Windows Taskmanager.

If the memory leak can be observed like this, there remains to be analyzed where the leak occurs: in Toga, in Python.net or even in the Winforms library?

**Comment by freakboy3742** [comment] 2022-05-11 23:14
With almost 100% certainty, it's Python.net; the only only wiggle room that might exist is around whether Toga is missing a call to a Python.net API that is needed to free memory. I'd be deeply surprised if it's Winforms, because the rest of the Windows developer ecosystem would be raising merry hell if it were a property of Winforms itself. Comparisons with memory consumption of CLI apps aren't helpful - it's like saying "my car has an oil leak - but my horse doesn't leak oil at all!". The issue is with the Python.net bridge. Unless your CLI app is also using a Python.net bridge, there's no comparison to be made.

The behaviour you're seeing here is entirely consistent with what has been previously reported: an app with nothing but button handlers leaks "just sitting there". The good news is that it appears you've found the way to make the problem worse by adding more buttons - that's very helpful, because *slow* leaks are almost impossible to track against the background noise of the Python and .NET garbage collector.

Historically, the source of the leak was tracked down to the internal event loop that runs maintaining asyncio. You can confirm if this is the case by re-applying the change from #1109 - this change *disables* asyncio handlers, but it should stop the leak (because the thing that is the root cause of the leak is stopped).

The other thing worth trying is the patch that was part of #1337 - that patch *enables* asyncio, but does more aggressive and explicit garbage collection. My testing came to the conclusion that this wasn't needed; but if it resolves your problem, then it might be worth adding back in (and reporting upstream to Python.net with a reproduction case).

**Comment by saroad2** [comment] 2022-05-12 05:19
Hey everyone, long time :)

The people over at Python.net claim very firmly that the memory leak problem that was introduces in their library was fixed in the latest version. If we have a way to reproduce that leak with Python.net code only, it's important to share it with them and show them that the leak was not yet fixed, better before they release the 3.0.0 version (not that I think it will happen any time soon...)

It's been suggested before to try and replace the backend of Toga Winforms with another library other than Python.net.
Maybe it's time to reconsider that.

**Comment by t-arn** [comment] 2022-05-13 05:44
My calculator is using pythonnet-3.0.0a2
If you want to try yourselves, the app can be found here: www.tanapro.ch > Downloads > taRpnCalcTG

**Comment by t-arn** [comment] 2022-05-13 05:51
Now, that's interesting: I just re-built my venv with Python 3.9 and ran `briefcase dev` and the memory consumption does NOT increase!

**Comment by freakboy3742** [comment] 2022-05-13 05:55
@t-arn What Python version were you using to see the memory leak? Although Python.net 3.0.0 isn't version dependent, they've been doing all their development on Python 3.9 and 3.10, so if you were using an older version of Python, it's possible there might be something in the interaction between that version of Python and Python.net that is the issue.

**Comment by t-arn** [comment] 2022-05-13 05:58
The packaged and published version uses Python 3.8

I will create a new package using Python 3.9 and check if the memory consumption is stable in the packaged version as well

**Comment by t-arn** [comment] 2022-05-16 19:40
I can confirm that the memory consumption is stable using Python 3.9

**Comment by saroad2** [comment] 2022-05-17 06:17
That's very interesting!

I believe that if that the case we should consider one of the followings:
1. Ask Pythonnet to fix the leak in Python 3.8
2. Drop Python 3.8 support for windows and support only Python 3.9+

I understand that 2 is problematic, but 1 might take some time. In the meanwhile, we should add a warning in the documentation that Python 3.8 and bellow has a leak. Moreover, we should probably keep this issue open but change the its name to "Memory Leak in Windows using Python 3.8".

**Comment by freakboy3742** [comment] 2023-04-15 05:43
I'm going to close this as WONTFIX. The problem has evidently been addressed in Python3.9+; Fixing a problem for one version of Python that will be EOL soon enough doesn't seem like something we're likely to address.

**Closed by freakboy3742** 2023-04-15 05:43 UTC
Labels: bug, windows
