### ISSUE TITLE
self.loop.run_forever Issue in app.py 

### ISSUE THREAD

**Issue by B-Mbengue** [beeware/toga#775] opened 2020-01-10 11:44 UTC
Hi
I am a beginnner in a beeware and I am trying to make  a application with beeware by using the example given in the documentation. 
When I run the "briefcase dev" command the application shows up but exits as soon as I click on a button.

## Current Behavior
Traceback (most recent call last):
Traceback (most recent call last):
  File "c:\users\abco1\appdata\local\continuum\anaconda3\envs\test3\lib\site-packages\toga_winforms\app.py", line 133, in run_app
    self.loop.run_forever(self.app_context)
  File "c:\users\abco1\appdata\local\continuum\anaconda3\envs\test3\lib\site-packages\toga_winforms\libs\proactor.py", line 90, in run_forever
    WinForms.Application.Run(self.app_context)
  File "c:\users\abco1\appdata\local\continuum\anaconda3\envs\test3\lib\site-packages\toga_winforms\app.py", line 118, in app_exception_handler
    tb_end_pos = py_exc.StackTrace.index("\\n']   at Python")
ValueError: substring not found

## Environment

* Python Version 3.7.6

* Operating System and Version 
  - Windows 10

* Toga Version 0.3.0

* Toga Target 

  - android

**Comment by freakboy3742** [comment] 2020-01-10 23:18
Thanks for the report!

This error is caused because something in your code is throwing an exception... and then Toga's error handling is internally raising an error trying to report your error. So - there's two bugs that need to be fixed here - but it's hard for you to fix your bug until Toga gives you better details on what your error actually *is*.

However, I haven't been able to reproduce the error that you're seeing. I suspect that this is due to something specific about your install of Python. I doubt you've done anything *wrong* in the way you've installed Python - it's just different to the environments where we are testing.

The stack track you've provided finishes on line 118 of app.py. Would you be able to edit that file, and add some debugging - printing the value of `py_exc.StackTrace` at that point? That will give us some hints as to why Toga's error reporting is failing.

I'll also flag that the Android target won't work (at least, not yet). We're currently rebuilding our Android support, and for the moment at least, Android support has been disabled in briefcase. This should be fixed in the coming months - we've got a contractor looking at the problem.

**Comment by B-Mbengue** [comment] 2020-01-13 10:21
Thanks @freakboy3742 !
I have found where was the issue. The error didn't come from python's environments. Like suggested, I have printed the value of py_exc.StackTrace. You  did that in the app.py file (generated automaticly)  but python didn't showed it up because there was a error before that line. This is the error I got "unsupported operand type(s) for ^: 'float' and 'float' " . I have  changed the sequence of the code by printing the error message before some operations.
Below the changes I made in bold :

def app_exception_handler(self, sender, winforms_exc):
        # The PythonException returned by Winforms doesn't give us
        # easy access to the underlying Python stacktrace; so we
        # reconstruct it from the string message.
        # The Python message is helpfully included in square brackets,
        # as the context for the first line in the .net stack trace.
        # So, look for the closing bracket and the start of the Python.net
        # stack trace. Then, reconstruct the line breaks internal to the
        # remaining string.
        print("Traceback (most recent call last):")
        py_exc = winforms_exc.get_Exception()
        **print(py_exc.Message)**
        tb_end_pos = py_exc.StackTrace.index("\\n']   at Python")
        tb_str = py_exc.StackTrace[2:tb_end_pos]
        for level in tb_str.split("', '"):
            for line in level.split("\\n"):
                if line:
                    print(line)
        print(py_exc.Message)

Hope this will help you for future update.

**Comment by freakboy3742** [comment] 2020-01-14 00:15
Good to know you've found the source of the problem - but I'd still like to see the content of the stack trace if possible. Even a single "unsupported operation" *should* contain a full stack trace, and the original bug you found was caused because the stack trace wasn't matching the `"\n'] at Python"` pattern. I'd be interested to see what the error content (py_exc.StackTrace) actually *was* in your case.

**Comment by saroad2** [comment] 2020-03-07 14:56
Is there any intention to solve the missing `"\n'] at Python"` in the index command?
I have the same problem too, which causes me to not see my stacktrace error

**Comment by freakboy3742** [comment] 2020-03-07 23:30
@saroad2 I'd be delighted to fix the problem - as soon as I have a way to reproduce it. My own testing doesn't reveal the problem, which is why I asked for the original error content. If you're able to provide that content, then I'll gladly work on a fix.

**Comment by saroad2** [comment] 2020-03-09 22:01
It is reproducing on my computer all the time.
You want me to fix it?

**Comment by freakboy3742** [comment] 2020-03-10 00:23
If you think you can fix it, then go right ahead! I'd still like to understand exactly what the difference/discrepancy is, though - if only so I'm aware of the variations that exist in the real world.

**Comment by freakboy3742** [comment] 2020-03-14 05:55
Fixed by #830.

**Closed by freakboy3742** 2020-03-14 05:55 UTC
