### ISSUE TITLE
Toga-Demo is unable to run in Ubuntu under Windows Subsystem for Linux

### ISSUE THREAD

**Issue by fphhotchips** [beeware/toga#435] opened 2018-03-26 08:24 UTC
## Expected Behavior
After installing the toga-demo package through pip, the running toga-demo should result in a working toga-demo display (or, possibly, a failure to display because no X server is available).

## Current Behavior
The following exception is raised.

```
Creating symlink (/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/gi & /home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/pygtkcompat) to system GTK+ libraries...
Creating symlink (/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/gi & /home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/pygtkcompat) to system GTK+ libraries...
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga_gtk/app.py", line 7, in <module>
    import gi
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga_gtk/app.py", line 52, in <module>
    os.symlink(gi_path, gi_symlink_path)
FileExistsError: [Errno 17] File exists: '/usr/lib/python3/dist-packages/gi' -> '/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/py3env/bin/toga-demo", line 7, in <module>
    from toga_demo.__main__ import run
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga_demo/__main__.py", line 2, in <module>
    from toga_demo.app import main
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga_demo/app.py", line 4, in <module>
    import toga
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga/__init__.py", line 114, in <module>
    set_platform()
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga/__init__.py", line 86, in set_platform
    local_vars['platform'] = importlib.import_module(module_name)
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga_gtk/__init__.py", line 2, in <module>
    from .app import *
  File "/home/user/miniconda3/envs/py3env/lib/python3.6/site-packages/toga_gtk/app.py", line 63, in <module>
    raise RuntimeError("Unable to automatically create symlink to system Python GTK+ bindings.")
RuntimeError: Unable to automatically create symlink to system Python GTK+ bindings.
```

## Steps to reproduce

1. Activate and install Ubuntu under the Windows Subsystem

2. Using Miniconda under Ubuntu, create an environment with only Python 3 and activate it

3. Use pip to install toga-demo

4. Run toga-demo

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [X] Linux - distro: Ubuntu    - version:  Ubuntu 16.04.2 LTS
  - [X] Windows - version: Win 10, Version 1709,  Build 16299.125
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [X] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [X] Other (please specify)

  (Running toga-demo under Ubuntu on WSL...)

**Comment by uranusjr** [comment] 2018-03-26 09:56
This is likely not a Toga issue. You need to jump through [a lot of hoops](https://virtualizationreview.com/articles/2017/02/08/graphical-programs-on-windows-subsystem-on-linux.aspx) to run graphical applications on WSL, and even if you do that things are not guarenteed to work. The very long discussion in Microsoft/WSL#637 can give you a rough idea of the situation.

**Comment by pyeguy** [comment] 2018-03-30 18:00
I think this might be related to Anaconda (or miniconda in @fphhotchips case)  Python distro. I'm on Ubunutu 16.04 with Anaconda 3.6 as the base python and am getting the same behavior :

```
(beeware) cpye@CamUbuntu                                                                                                                                                                                                             [~]
🌶️ toga-demo
Traceback (most recent call last):
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga_gtk/app.py", line 7, in <module>
    import gi
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga_gtk/app.py", line 52, in <module>
    os.symlink(gi_path, gi_symlink_path)
FileExistsError: [Errno 17] File exists: '/usr/lib/python3/dist-packages/gi' -> '/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cpye/.virtualenvs/beeware/bin/toga-demo", line 7, in <module>
    from toga_demo.__main__ import run
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga_demo/__main__.py", line 2, in <module>
Creating symlink (/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/gi & /home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/pygtkcompat) to system GTK+ libraries...
    from toga_demo.app import main
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga_demo/app.py", line 4, in <module>
    import toga
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga/__init__.py", line 114, in <module>
    set_platform()
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga/__init__.py", line 86, in set_platform
    local_vars['platform'] = importlib.import_module(module_name)
  File "/home/cpye/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga_gtk/__init__.py", line 2, in <module>
    from .app import *
  File "/home/cpye/.virtualenvs/beeware/lib/python3.6/site-packages/toga_gtk/app.py", line 63, in <module>
    raise RuntimeError("Unable to automatically create symlink to system Python GTK+ bindings.")
RuntimeError: Unable to automatically create symlink to system Python GTK+ bindings.

```

**Comment by danyeaw** [comment] 2018-04-01 01:17
Thanks for reporting this issue. I have never used anaconda before, but I did attempt to reproduce the problem using miniconda3 in Ubuntu, but I don't have an installation of WSL to try. Unfortunately, I wasn't able to reproduce this issue:

    bash Miniconda3-latest-Linux-x86_64.sh
    conda create --name toga-demo
    source activate toga-demo
    pip install toga-demo
    toga-demo

The toga-demo launched just fine with no warnings. It also worked with the pre-release version with:

    pip install --pre toga-demo

Since the warnings are about symlinks to PyGObject, have you tried to install it via conda?

    conda install -c conda-forge pygobject

**Comment by danyeaw** [comment] 2018-04-04 23:34
@pyeguy It sounds like you have no version of Gtk+ installed. What happens when you try to apt-get install Gtk+?

    sudo apt install python-gi python-gi-cairo python3-gi python3-gi-cairo gir1.2-gtk-3.0

You could try to build Gtk+ from source:

    git clone git://git.gnome.org/jhbuild
    cd jhbuild
    ./autogen.sh
    make
    make install
    PATH=$PATH:~/.local/bin
    jhbuild build gtk+

**Comment by olf42** [comment] 2018-05-30 15:48
I'm on Ubuntu 16.04 and can only reproduce this (first mentioned) error with https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html when using Python3.6.5. On Python3.5.2 it works fine. Inheriting system packages into the virtualenvs made no difference.

**Comment by diramazioni** [comment] 2018-07-08 10:39
I'm on Ubuntu 17.10 same issue. I've tried with and without conda, fresh virtualenv with python 3.5 
[toga_demo_error_log.txt](https://github.com/pybee/toga/files/2173631/toga_demo_error_log.txt)

It works on python 3.6 so I'm reporting the exact opposite as what @olf42 reported...

**Comment by freakboy3742** [comment] 2018-07-08 23:58
@diramazioni Can you confirm what version you have installed? If you're running 0.2.15, you're going to have problems; but if you're running 0.3.0.dev9, you should have more luck.

**Comment by diramazioni** [comment] 2018-07-09 07:40
@freakboy3742 as you can see from the log I was trying with 0.2.15 pulled by pypi

**Comment by freakboy3742** [comment] 2018-07-09 23:04
@diramazioni Right - in which case, you're going to have problems :-) Toga-demo under Toga 0.2.15 really only worked on macOS.

**Comment by freakboy3742** [comment] 2018-07-09 23:06
Apologies - hit the wrong button. 

@diramazioni I don't know much about the Ubuntu subsystem, but based the approach Toga 0.2.15 used to configure itself in a virtual environment would not work. The approach has been changed in the 0.3.0 development branch.

**Comment by diramazioni** [comment] 2018-07-16 08:13
Sorry for the delay, in the mean time I had to build the ui using another widget-kit.
But I don't like to leave loose report and I'd really like to try out pybee (I found the idea great and the effort huge)
I've briefly tried to clone the toga master and setup install it but it fails to find a valid link for toga-gtk==0.3.0.dev10 here is the log
[toga-master_setup_install.txt](https://github.com/pybee/toga/files/2196870/toga-master_setup_install.txt)
I'll try to voice myself on gitter and I remark that toga-demo works with Toga 0.2.15 and python 3.6

**Comment by suryatmodulus** [comment] 2019-09-02 06:36
This might solve the issue while using anaconda environments:
pip install --pre toga --user

**Comment by suryatmodulus** [comment] 2019-09-02 06:38
This might solve the issue in anaconda environments:
pip install --pre toga --user

**Comment by freakboy3742** [comment] 2020-04-25 09:12
I'm going to close this; there are a couple of examples in this thread that suggest toga *can* work under WSL, provided the WSL environment is configured correctly.

**Closed by freakboy3742** 2020-04-25 09:12 UTC
