### ISSUE TITLE
Application crash on no "open_document" command in MacOS

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#864] opened 2020-04-25 19:37 UTC
This issue is a followup to beeware/rubicon-objc#170

## Background
I developed a GUI on windows platform using *Toga* named [Eddington](https://github.com/EddLabs/eddington_gui). When I try to run my application on macOS it crashes with the following error:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rubicon/objc/api.py", line 232, in __call__
    result = self.py_method(py_self, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/toga_cocoa/app.py", line 72, in application_openFiles_
    self.impl.open_document(str(fileURL.absoluteString))
AttributeError: 'App' object has no attribute 'open_document'
```

## Steps to reproduce
1. Checkout to branch **dev**
2. On file *src/eddington_gui/\_\_init\_\_.py* comment out the usage of *wxAgg* in *matplotlib*
3. Download [sagi.txt](https://github.com/beeware/toga/files/4533860/sagi.txt)
4. Change the suffix from ".txt" to ".csv" (github doesn't allow to upload csv files to issues )
5. Open Eddington using "briefcase dev" and the GUI will open.
6. Next to the "input" line press the "choose file" button and choose the "sagi.csv" file you just downloaded.
7. Press the "plot data" button below and a *matplotlib* graph window would show up.
8. Close the graph window using the "x" button
9. The bug reproduces.

## Your Environment
I'm using MacBook pro with Catalina 10.15.3 and Python 3.7

  - [X] macOS - version:
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash) - latest

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [X] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment] 2020-04-26 04:10
Thanks for the report. It would be really helpful if you (or anyone who wants to investigate) could pare this back to a simple test case that isn't bound up in the logic of Eddington.

My suspicion is that this bug will be due to application lifecycle, and closing the main app window not causing the application to close. The `open_document` callback should only be invoked on a document based app because a "single main window" app shouldn't ever be in a state where the window doesn't exist.

**Comment by saroad2** [comment] 2020-04-26 06:18
Here is a simpler exmample:

Copy the following app
```python
import toga
import numpy as np
import matplotlib.pyplot as plt


class ExampleApp(toga.App):
    def startup(self):
        # Set up main window
        self.main_window = toga.MainWindow(title=self.name, size=(148, 200))

        box = toga.Box(children=[
            toga.Button(
                "Plot some plot", on_press=self.plot_something
            )
        ])

        # Add the content on the main window
        self.main_window.content = box

        # Show the main window
        self.main_window.show()

    def plot_something(self, widget):
        x = np.arange(1, 100)
        y = 2 * x + 1

        plt.plot(x, y)
        plt.show()


def main():
    return ExampleApp('App', 'org.beeware.dummy')


if __name__ == '__main__':
    main().main_loop()

```

Once the bug in *rubicon-objc* is fixed (adding the *None* variable to line 638 in *eventloop.py*) this bug is reproduced.

**Comment by freakboy3742** [comment] 2020-04-26 07:26
Ok - I'm seeing different behavior (on macOS Mojave). With Rubicon 0.3.1, I see the crash that you originally reported (the `terminate:` problem); however when I use the patched version of Rubicon, I get the following when I *open* the plot window:

```
2020-04-26 15:14:32.468 python[14628:10517366] -[NSApplication transformToForegroundApplication]: unrecognized selector sent to instance 0x7fb89e4c6220
objc[14628]: Invalid or prematurely-freed autorelease pool 0x7fb89b993298.
```
This puts the app into weird state where it beachballs; and even if I force-kill the macOS app, the window persists (in it's beachballed state), and even a force kill of the python process doesn't make the window go away. Eventually it appears to disappear of it's own accord.

I very strongly suspect the problem is actually matplotlib - or, more specifically, the wxwindows rendering backend for matplotlib, and it's interaction with Toga. Matplotlib is trying to display a GUI; as such, it's using wxwindows as a GUI framework. This means that there are two GUI frameworks competing for control of the app lifecycle. I'm seeing that manifest as a failure when wxwindows tries to open the app; you're seeing this as the "open_document" error (which is caused because the Toga app is being sent a signal that it shouldn't ever get unless it has been explicitly created as a Document-based app.

I'm very strongly tempted to call this a wontfix - on the basis that it's an interaction of two libraries that *shouldn't* ever need to interact. I recognize that is challenging for your specific use case - but I'd argue your app is doing the wrong thing in the first place by mixing two GUI frameworks. For my money, the real fix is to use a non-wxwindows backend for matplotlib; either a direct Toga backend, or an image-based backend that renders to a PNG that Toga displays.

**Comment by saroad2** [comment] 2020-04-26 10:10
Hey,

The moment *Toga* will support `Canvas` for Windows, i will start using [Toga Chart](https://github.com/beeware/toga_chart) instead of wxwindows for all platforms.

I gave it a try as described in issue #865, but I didn't manage to succeed finding the right design to incorporate Winform Graphics with the *Toga* API.  Once this is taken care of, I will switch using `Canvas`.

You can close the issue if you feel like it, but I was hoping someone would have some quick-fix until I could use `Canvas`.

**Comment by freakboy3742** [comment] 2020-04-27 03:05
Yeah - I don't think there's a quick fix here. There are two GUI frameworks wrestling for control of the app; that's not going to be easy to resolve. If there *is* a fix, I suspect it will be on the matplotlib/wxwindows side in this instance; Toga is the app, so it is the part that should be "in control"; the matplotlib window should be "just a window", and not doing anything with application lifecycle.

Sorry I can't offer a better option here; hopefully someone will take the bait on canvas for Windows and make your life a lot easier.

**Closed by freakboy3742** 2020-04-27 03:05 UTC
Labels: up-for-grabs
