### ISSUE TITLE
Remove Menubars

### ISSUE THREAD

**Issue by Ksengine** [beeware/toga#1152] opened 2020-12-05 10:37 UTC
Menubar and menus are old GUI fashions. 
There are new methods to replace this.

Toga automatically adds menubar to app.
If user wants to create window without menubar?

Commands are useful to things like keyboard shortcuts.

Ribbons and menu buttons are alternatives to menubar.
I suggests ribbons.

**Comment by freakboy3742** [comment] 2020-12-05 23:21
"Fashion" isn't a consideration here. Toga aims to adhere to the Human Interface Guidelines (HIG) for each platform:

 * [macOS](https://developer.apple.com/design/human-interface-guidelines/macos/overview/themes/) 
 * [iOS](https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/)
 * [Windows](https://docs.microsoft.com/en-us/windows/uwp/design/)
 * [GTK/Gnome](https://developer.gnome.org/hig/stable/)
 * [Android](https://developer.android.com/design/index.html)
 
On platforms like macOS, for example, removing menubar isn't an option *at all*. Menus are a core part of how macOS operates. 

However, you'll also note that the Toga API *does not* include any public API for creating menus. This is by design, as it allows each platform to determine the most appropriate way to represent the high level concepts required by an application.

For example - every application needs a command to Quit the app. For any given platform, we need to determine what that command is named (is it "Quit"? "Exit"? "Exit MyApp"?). We also need to determine where that menu item appears - is it under an application menu? Under the File menu? Or somewhere else entirely? 

Closing this ticket on the basis that a blanket "Remove menubar" proposal is a non-starter, as is "Add ribbons". Any proposal for changing how commands manifest needs to be in the specific context of a platform and its HIG.

**Closed by freakboy3742** 2020-12-05 23:21 UTC
Labels: enhancement

**Comment by Ksengine** [comment] 2020-12-06 01:44
macos needs a menubar.

Windows and linux users can quit apps easily.
We can include help icon on window border.

Many modern apps haven't menus. Even microsoft apps are using ribbons.

**Comment by freakboy3742** [comment] 2020-12-06 09:34
I refer you to my earlier comments, which you either haven't read, haven't understood, or have chosen to ignore.

If you would like clarification on anything I've said, I'm happy to answer questions. However, I'm not going to respond to blanket statements that ignore advice and direction that I've provided.

**Comment by freakboy3742** [comment] 2020-12-06 09:35
I'm also not especially inclined to respond to single line sentences that don't clearly articulate a position, or make a detailed proposal.

**Comment by Ksengine** [comment] 2020-12-06 10:12
> I refer you to my earlier comments, which you either haven't read, haven't understood, or have chosen to ignore.
> 
> If you would like clarification on anything I've said, I'm happy to answer questions. However, I'm not going to respond to blanket statements that ignore advice and direction that I've provided.

Sorry, my english knowladge is low.

**Comment by Ksengine** [comment] 2020-12-06 10:19
> For example - every application needs a command to Quit the app. For any given platform, we need to determine what that command is named (is it "Quit"? "Exit"? "Exit MyApp"?). We also need to determine where that menu item appears - is it under an application menu? Under the File menu? Or somewhere else entirely?

We will remove quit item from file menu, as window has a close button.
We will remove help menu,
- we can add help button to window border.
- or can you suggest a better way

**Comment by freakboy3742** [comment] 2020-12-06 22:13
"More the quit item from the file menu".

The quit item isn't *on* the file menu universally, and some platforms *require* a quit item as part of their HIG. 

Buttons on the window border aren't recommended UI for Windows *or* macOS.

I have already suggested a better way. Follow the HIG. Going forward, I'm going to ignore any suggestion you make that is not (a) platform specific, and (b) made with specific reference to that platforms HIG.

**Comment by Ksengine** [comment] 2020-12-07 16:13
Gtk hig recommends primary menus
See https://developer.gnome.org/hig/stable/primary-menus.html.en
