### ISSUE TITLE
can't set fonts in windows for all widgets

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1195] opened 2021-01-25 07:56 UTC
**Describe the bug**
At the moment, not all widgets can be set with a font in Windows, even though the font setting implementation is quite easy.
For example, `toga.Selection` widget can not be set with fonts at the moment.

This raised a flag that maybe we should reconsider how to implement font settings in all of our platforms.
See conversation in PR #1177 

**Environment:**
 - Operating System: Windows
 - Python version: 3.8.7
 - Toga: latest

**Comment by freakboy3742** [comment] 2021-01-26 04:34
Preserving the summary of the discussion from #1177:

We can't assume widgets will support `set_font()` by default; most widgets (e.g, `Divider`, `Switch`, most of the containers) have no concept of a font. If the base widget has a complete `set_font()` implementation, we would need to explicitly disable that implementation on every widget that doesn't have a font. We would also need to modify the implementation when the widget that has the font isn't labelled `native`.

However, when a widget *does* support fonts, the implementation will be *almost* identical - it will be platform specific, but will follow the general pattern of:

    def set_font(self, font):
        if font:
            self.native.font = font.bind(self.interface.factory).native

The target (self.native) will change on some widgets, but the required call is consistent. 

Therefore - on each platform, we should extract this general pattern as a utility method in the platform's `fonts` module where we can pass in the impl widget, the desired font, and the name of the native widget (with `native` as the default`), so that the widgets that *do* need font support can share a common implementation, but that implementation will be no more complex than:

    def set_font(self, font):
        set_font(self, font)

This allows us to ensure that the edge cases around setting fonts (such as clearing a font back to the default) are consistently handled everywhere that a font is specified, but doesn't introduce bugs where fonts aren't (or can't) be supported.

**Comment by osintalex** [comment] 2021-02-14 16:35
Hi! I'm a first-timer and I'd like to try helping with this if that's cool?

I've read through the issue a few time and had look at the fonts.py file in the iOS directory and a few others but still have a few questions about what exactly needs doing, so I'd really grateful for some guidance if you have time!

**Comment by freakboy3742** [comment] 2021-02-15 01:58
@osintalex Happy to help get you started as a contributor! Do you have any specific questions, or are you looking for general advice on getting started?

**Comment by osintalex** [comment] 2021-02-15 22:46
@freakboy3742 thanks, appreciate it! They're just specific questions about how to address this issue... I've popped them down below:

> Therefore - on each platform, we should extract this general pattern as a utility method in the platform's fonts module

I'm a bit confused where the fonts module is for each platform? I can see a general fonts module [here](https://github.com/beeware/toga/blob/master/src/core/toga/fonts.py) and then fonts.py files per platform as with android [here](https://github.com/beeware/toga/tree/master/src/android/toga_android). 

I'm guessing you mean I need to add this utility method in the fonts.py file in each of the platforms, i.e. on android, iOs, cocoa etc? 

> but that implementation will be no more complex than:

    def set_font(self, font):
        set_font(self, font)

Does this mean I literally just need to write a method that effectively copy and pastes the above into each of these font.py files for each platform? Or do I need to do something a bit more complex. Apologies in advance if I've misunderstood this.

Thanks in advance for your help!

**Comment by freakboy3742** [comment] 2021-02-15 22:59
@osintalex You're on the right track with the fonts modules - there's a fonts module in the `core` module that defines the public interface; and a version in each of the platform backends that provides the implementation for that platform; the locations you've mentioned are the right places.

The underlying problem here is that each platform has it's own API for setting fonts. However:
1. Not *every* widget can have a font set; 
2. Those widgets that do need fonts don't necessarily have a consistent name for the widget that needs a font set.  
3. The logic for setting a font is mildly complex.

Ordinarily, when there's a block of complex logic shared between subclasses, you'd put that logic into the base class and have every subclass inherit that logic; however, in this case, that approach fails because each implementation needs to be slightly different (to account for point 2) isn't needed at all on a lot of widgets (point 1)

So: the goal here is to define a single method that encapsulates the "complex" part of the font setting logic; and then invoke that method where it's needed, parameterised around the native widget that needs the font assigned. That lets us have an abstracted single implementation of the complex, platform specific "set font" logic; but we only use that logic on the widgets where it's needed; and where it is needed, we can specify which native widget needs to have the font applied.

The `set_font()` code snippet is the logic that will go into each of the platform widgets that needs to be able to set a font. The version of `set_font()` that is being *invoked* is the method that will go in `fonts.py`, providing the abstracted calls to actually set the font using native APIs.

Does that make more sense?

**Comment by osintalex** [comment] 2021-02-16 19:10
Hey, thanks for your reply and yes it's starting to make more sense, thanks for answering all my questions!

OK, so in terms of the outcomes you'd like to see from a contribution, is this about right?

1. A method in the fonts.py module that sits within the `core` module. This method will encapsulate the complex part of the font setting logic across all the different platform APIs for setting fonts, i.e. it will be applicable to every platform's API. It will do the 'heavy lifting' for setting a font but will not include tweaks specific for platforms; that comes later.
2. Within the fonts.py modules in specific platforms, invoke the method from 1 where it's needed to set fonts for native widgets and account for any differences particular to that platform through parametrisation; these are the 'tweaks' mentioned above.

If that's correct, it looks like I need to write a method that captures the complex part of the font logic and put this in the font module within the core module and then invoke this where appropriate in the fonts modules specific to each platform.

Is that about right?

**Comment by freakboy3742** [comment] 2021-02-17 01:19
@osintalex Close, but not quite. 

(1) from your description isn't required. There's no truly cross-platform "set font" API; every platform has it's own specific API. In addition, there's no *public* `Widget.set_font()` API (by design) - `set_font()` exists only as a platform-specific implementation API.

So - yes, there will be a per-platform implementation of the complex part of `set_font()` logic, encapsulated in the platform's `fonts` module; and each widget on a platform that needs font support will invoke that utility method.

**Comment by osintalex** [comment] 2021-02-20 22:36
Hi! Sorry I haven't replied earlier, busy work week! 

Thanks for taking the time to explain all that to me, I'll get working on a solution now.

**Comment by xy1989** [comment] 2021-10-13 19:51
I see this issue is still open. Let me know if it's open for me to claim and work on.

**Comment by freakboy3742** [comment] 2023-05-29 02:00
I'm going to close this ticket; the widget audit (which is nearing completion) adds, and explicitly checks font support on every widget, on every platform.

**Closed by freakboy3742** 2023-05-29 02:00 UTC
Labels: enhancement, good first issue
