### ISSUE TITLE
WeakrefCallable Class implementation is faulty

### ISSUE THREAD

**Issue by proneon267** [beeware/toga#2163] opened 2023-10-21 12:55 UTC
### Describe the bug

The WeakrefCallable class implemented in #2066 appears to be a faulty one. As such the items in the app menu do not work when clicked on. Moreover, the weakref.ref() calls added to the different places also appears to be problematic. The event handlers wrapped in weakref also do not fire.

### Steps to reproduce

1. Clone the latest main branch of the toga repository.
2. Install the cloned repo.
3. Create a default helloworld project in briefcase.
4. Run the project in dev mode.
5. Try to click on the menu items like "Exit".
6. The handlers attached to the menu items won't fire.

### Expected behavior

The app menu items like "Exit" should fire their attached handlers.

### Environment

- Operating System: Windows 11
- Python version: 3.10.6
- Software versions:
  - Briefcase: Latest
  - Toga: Latest from the main branch
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment] 2023-10-22 23:45
Thanks for the report. The weakref handlers are working fine AFAICT - the problem is that they're passing out of scope and being garbage collected. 

I've just added #2167 which should fix the problem.

**Comment by freakboy3742** [comment] 2023-10-22 23:47
I can't find any other event handlers that aren't working - they *should* all be tested by the testbed test suite. Menus and toolbars fell through the cracks because they're tested as part of toga.App, which is what #2075 will add tests for. 

If you've got any examples of events that aren't working, let us know and we can investigate - but it's almost certainly the same cause as the menu/toolbar issue.

**Comment by proneon267** [comment] 2023-10-23 00:39
Thanks, I'll report back if I find any such events.

**Closed** 2023-10-24 16:38 UTC
Labels: bug, windows
