### ISSUE TITLE
How to eliminate the problems that occur in running your first sample program?

### ISSUE THREAD

**Issue by haisheng666** [beeware/toga#1772] opened 2023-02-09 07:15 UTC
### Describe the bug

/opt/anaconda3/envs/bee_ware_project/lib/python3.9/site-packages/toga_gtk/app.py:43: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.native.set_wmclass(app.interface.name, app.interface.name)

(temperature.py:62029): Pango-CRITICAL **: 15:02:33.607: pango_font_description_set_size: assertion 'size >= 0' failed

### Steps to reproduce

run program

### Expected behavior

/opt/anaconda3/envs/bee_ware_project/lib/python3.9/site-packages/toga_gtk/app.py:43: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.native.set_wmclass(app.interface.name, app.interface.name)

(temperature.py:62029): Pango-CRITICAL **: 15:02:33.607: pango_font_description_set_size: assertion 'size >= 0' failed

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment] 2023-02-09 07:26
Duplicate of #1718.

**Closed by freakboy3742** 2023-02-09 07:26 UTC
Labels: bug, duplicate
