### ISSUE TITLE
Documentation for DetailedList seems incorrect; running example throws exception

### ISSUE THREAD

**Issue by phlummox** [beeware/toga#1403] opened 2022-01-09 12:20 UTC
**Describe the bug**

The [documentation][detailedlist-doc] for DetailedList seems to be incorrect. It suggests list items can have a dictionary key, "icon", which may map to an empty string, but running that code gives an exception. This suggests the documentation needs to be updated (and perhaps should have [doctests][doctest] regularly run on it, if they aren't already).

[detailedlist-doc]: https://github.com/beeware/toga/blob/2eea8fc476856e8bc66ba316434a0c5e3f192005/src/core/toga/widgets/detailedlist.py#L25
[doctest]: https://docs.python.org/3/library/doctest.html

**To Reproduce**

1. Install briefcase. (I used 'pip install briefcase' in a virtualenv under Python 3.8.) 
2. Create a new project with `briefcase new`.
3. Add a function `list_test()` to the `app.py` file:

   ```python
   def toga_test():
     dlist = toga.DetailedList(
          data=[
             {
                 'icon': ''
                 'title': 'John Doe',
                 'subtitle': 'Employee of the Month',
                 'pk': 100
              }
          ]#,
          #on_select=selection_handler
       )
   ```
4. Install toga and other dependencies: `briefcase dev --no-run`
5. Start a python repl and execute the `app.py` file: \
   `exec(open("src/my_app_folder/app.py").read())`
6. Run the toga_test() function: `toga_test()`.

**Expected behavior**

... Any non-error behaviour would be good :-). If the docstrings contained enough scaffolding code to actually display the widget, that would be even better.

**Actual behavior**

```
Python 3.8.0 (default, Dec  9 2021, 17:53:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exec(open("src/larder_reading_list_cli/app.py").read())
>>> toga_test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 53, in toga_test
  File "/home/user/myapp/env/lib/python3.8/site-packages/toga/widgets/detailedlist.py", line 63, in __init__
    self.data = data
  File "/home/user/myapp/env/lib/python3.8/site-packages/toga/widgets/detailedlist.py", line 88, in data
    self._impl.change_source(source=self._data)
  File "/home/user/myapp/env/lib/python3.8/site-packages/toga_gtk/widgets/detailedlist.py", line 82, in change_source
    self.row_factory(item))
  File "/home/user/myapp/env/lib/python3.8/site-packages/toga_gtk/widgets/detailedlist.py", line 68, in row_factory
    return TextIconRow(self.interface.factory, self, item)
  File "/home/user/myapp/env/lib/python3.8/site-packages/toga_gtk/widgets/internal/rows/texticon.py", line 18, in __init__
    self.icon = self.get_icon(self.interface, self.factory)
  File "/home/user/myapp/env/lib/python3.8/site-packages/toga_gtk/widgets/internal/rows/texticon.py", line 58, in get_icon
    row.icon.bind(factory)
AttributeError: 'str' object has no attribute 'bind'
```

**Environment:**
 - Operating System: Linux (Ubuntu 18.04)
 - Python version: 3.8.0
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30

**Additional context**

Bug report #772 suggests `None` might work instead of a `str`.

**Comment by freakboy3742** [comment] 2022-03-29 06:39
Closing as a duplicate of #772 - the documentation of DetailedList is definitely lacking.

**Closed by freakboy3742** 2022-03-29 06:39 UTC
Labels: bug
