### ISSUE TITLE
 DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead generate and DeprecationWarning: Gtk.Misc.set_alignment is deprecated the generate Android App

### ISSUE THREAD

**Issue by diegolisboadev** [beeware/toga#1167] opened 2020-12-12 22:28 UTC
**DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead**

  def _make_subprocess_transport(self, protocol, args, shell,

**DeprecationWarning: Gtk.Window.set_wmclass is deprecated**

  self.native.set_wmclass(app.interface.name, app.interface.name)
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()

**DeprecationWarning: Gtk.Misc.set_alignment is deprecated**

  self.native.set_alignment(*gtk_alignment(value))
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.clear_error()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.clear_error()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()

**Comment by freakboy3742** [comment] 2020-12-13 00:27
Thanks for the report. The wm_class warning has been reported as part of #1147; the `set_alignment` and `@coroutine` warnings are also ones that I have also seen.

The `@coroutine` one in particular is an odd one, because AFAICT, Toga itself isn't using @coroutine anywhere in its codebase, and the stacktrace doesn't provide enough context to work out the underlying culprit.

**Comment by freakboy3742** [comment] 2020-12-13 00:37
Marking this for first timers because identifying the exact lines causing these deprecations, and hunting down the non-deprecated replacements could make a fun first-timer exercise.

**Comment by diegolisboadev** [comment] 2020-12-13 01:06
I will debug the code in more detail, it will be another interesting challenge

**Comment by Vipul-Cariappa** [comment] 2021-02-05 11:26
@freakboy3742 `DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead` is not caused by `toga` it is caused by gbulb module which is one of the dependency of Gtk. 
Link to Github: https://github.com/nhoad/gbulb
The project was last updates on Jan 2019 and is not being maintained.
Location of the function: `venv/lib/python3.8/site-packages/gbulb/glib_events.py` line no 321
I am not 100% sure but looks like the `@coroutine function` is never called. I remove the function and the application run as expected.
I hope you found this helpfull.

**Comment by freakboy3742** [comment] 2021-02-05 23:38
@Vipul-Cariappa Thanks for getting to the bottom of that... and thanks for drawing our attention to the fact that it's no longer maintained. Since we're dependent on that functionality, we may need to look into adopting/forking gbulb...

**Comment by freakboy3742** [comment] 2021-09-30 04:46
An update: As Gbulb is not being maintained, it looks like James Henstridge (who is well known in the GTK community) has [developed an alternative](https://github.com/jhenstridge/asyncio-glib/).

From the API docs, it looks like it should be a very minor change to adopt asyncio-glib over Gbulb - we only need to modify the event loop initialisation code in Toga-GTK's `app.py`, following the instructions given in the asyncio-glib repo.

**Comment by freakboy3742** [comment] 2021-10-02 03:58
From some investigation, asyncio-glib may not be appropriate here, as it doesn't have full GTKApplication integration.

**Comment by freakboy3742** [comment] 2021-10-24 01:04
BeeWare has now taken over ownership of Gbulb; as of the 0.6.2 release, this `coroutine` issue has been resolved. The `set_wmclass` warning is still current.

**Comment by leggewie** [comment] 2022-02-16 19:06
@freakboy3742 I see that you added the set_app function in src/gtk/toga_gtk/app.py in 67d2a5f526d95fd954fe65 in 2017 and the comment shows it being deliberate despite it being deprecated.  FWIW, my tests were unable to confirm the necessity of this code.  I even went so far as to remove the entire set_app function.  To no ill effect and the application name stayed "Hello World", too.  Can you provide a test case?

**Comment by freakboy3742** [comment] 2022-02-16 22:19
@leggewie I suspect this might be highly distribution dependent. Using Ubuntu 20.04, running Toga Tutorial 0, using `python -m tutorial`, this is what I see with the current Toga release:
<img width="475" alt="Screen Shot 2022-02-17 at 6 16 16 am" src="https://user-images.githubusercontent.com/37345/154366745-3d9181f9-0a90-4e6d-b9ad-738dfccfc6cf.png">

If I comment out the `set_wmclass` call, this is what I see:
<img width="526" alt="Screen Shot 2022-02-17 at 6 15 48 am" src="https://user-images.githubusercontent.com/37345/154366735-8595220f-9a25-40ec-adb2-92f47512a245.png">

**Comment by leggewie** [comment] 2022-02-17 12:09
I was running focal myself until very recently, I'm now on Jammy.  I'd say, that makes it fairly close.  I'm not sure it's the distro, but maybe the DM (I run unity, but I also tried with budgie) or some local configuration.  I've attached a[ minimal helloworld "project"](https://github.com/beeware/toga/files/8088484/hw.tar.gz) that works fine for me without set_wmclass.  Can you confirm how it behaves for you?  Can you even try in a temporary guest account to rule out local configuration interference?

**Comment by freakboy3742** [comment] 2022-02-17 23:23
This is an Ubuntu 20.04 box that I use exclusively for testing Linux configurations. It's entirely default "as installed" configuration other than installing Python et al to get the code running. I see this behavior on any app, including your minimal helloworld, on any user account.

**Comment by freakboy3742** [comment] 2023-04-03 02:57
Closing in favour of #1718.

**Closed by freakboy3742** 2023-04-03 02:57 UTC
Labels: bug, good first issue, linux
