### ISSUE TITLE
Tutorial 4 does not run on Windows 10 (Python 3.7 64-bit)

### ISSUE THREAD

**Issue by BrendanSimon** [beeware/toga#743] opened 2019-09-30 12:20 UTC
Tutorial 4 does not run on Windows 10 (Python 3.7 64-bit)

https://toga.readthedocs.io/en/latest/tutorial/tutorial-4.html

I get the following error:

```python
python -m draw
Traceback (most recent call last):
  File "D:\Brendan\Temp\toga\venv\lib\site-packages\toga_winforms\app.py", line 120, in run_app
    self.create()
  File "D:\Brendan\Temp\toga\venv\lib\site-packages\toga_winforms\app.py", line 56, in create
    self.interface.startup()
  File "D:\Brendan\Temp\toga\draw.py", line 15, in startup
    self.canvas = toga.Canvas(style=Pack(flex=1))
  File "D:\Brendan\Temp\toga\venv\lib\site-packages\toga\widgets\canvas.py", line 515, in __init__
    self._impl = self.factory.Canvas(interface=self)
AttributeError: module 'toga_winforms.factory' has no attribute 'Canvas'
```

**Comment by BrendanSimon** [comment] 2019-09-30 12:24
same as #498 ?

**Comment by danyeaw** [comment] 2019-10-02 01:35
@BrendanSimon Yes, this is the same issue. The Canvas widget is not yet supported in Windows, so this is an expected error. Notice that the supported platforms table in the API docs shows no current Windows support: https://toga.readthedocs.io/en/latest/reference/api/widgets/canvas.html

**Comment by freakboy3742** [comment] 2019-10-02 02:40
Closing as a duplicate of #498

**Closed by freakboy3742** 2019-10-02 02:40 UTC
Labels: duplicate
