### ISSUE TITLE
Reduce repetition in event handler testing

### ISSUE THREAD

**Issue by bruno-rino** [beeware/toga#1965] opened 2023-06-06 15:47 UTC
### What is the problem or limitation you are having?

I'm looking at the pytest code. The test for event handlers seems to be always identical. Instead repeated code, maybe we could have a helper function to handle it?

### Describe the solution you'd like

Something like this:

```
def _test_event(widget, name):
    # No handler initially
    assert getattr(widget, f'_on_{name}')._raw is None

    # Define and set a new callback
    handler = Mock()

    setattr(widget, f'on_{name}', handler)

    assert getattr(widget, f'on_{name}')._raw == handler

    # Invoke the callback
    getattr(widget._impl, f'simulate_{name}')()

    # Callback was invoked
    handler.assert_called_once_with(widget)
```

### Describe alternatives you've considered

That's it. The function needs a better name though.

**Comment by freakboy3742** [comment] 2023-06-06 22:44
I understand the motivation; and I won't argue that there's a lot of repetition in the tests. however, broadly speaking, I'm not a huge fan of complex behavioural test helpers like this, for a couple of reasons:

1. Any logic in a test is itself logic that then needs to be tested
2. It frequently falls victim of "this pattern is identical, except when it isn't - so you end up either reproducing the test logic anyway, or making the test utility *more* complex over time (adding in support for the special cases).

There's two alternate approaches to this problem that I'm more inclined to follow:

1. Refactoring *assertions* as utilities. If a test needs to assert width, height, x and y, then a single "assert rectangle" method simplifies logic considerably. The difference here is that the refactored method is ultimately passive - it doesn't modify anything, it's just a wrapper around a set of assertions - so the risk of "getting the logic wrong" is lower - worst case, you don't assert something you should.
2. If a *test* reveals a consistent logic pattern, then refactor the underlying business logic so there is only a need for a single test. In the specific example you've given - events - there is a ticket describing the problem (#797), and an attempt to address the problem in #804. That PR moved to a declarative structure for events - a widget would use a single line to declare the events that it emitted, and all the handlers needed would be added automatically. This reduces the testing burden to (a) does event registration work as expected? and (b) does each widget register the right events?

The code has drifted a bit since #804; but at the time, I was happy with the approach that PR was taking. If you're interested in cleaning up this aspect of the code, resurrecting that approach would be my suggestion. 

On that basis, I'm going to close this ticket in favor of #797, as it seems like a better overall target for refactoring.

**Closed by freakboy3742** 2023-06-06 22:44 UTC
Labels: enhancement
