### ISSUE TITLE
Working dev app has iOS errors "[iOS] Not implemented" Canvas class methods

### ISSUE THREAD

**Issue by michhar** [beeware/toga#1157] opened 2020-12-07 00:34 UTC
**Describe the bug**

Hi.  I am creating an iOS app with `toga` and `briefcase` and so far have a very simple working app that "draws" a triangle wherever the user clicks on a  Canvas.  The app functions as expected in dev mode, as well as, as a macOS app, however, when I build for iOS and run in Xcode I see "Not implemented" errors for class methods of `toga`'s Canvas widget class.  I'm checking to see if I am missing something as I'm new to Toga.  Thanks in advance for your help and let me know if I can provide more context.

**To Reproduce**

1. Create a `briefcase` project with a `toga` app containing a Canvas widget.  e.g. (in `def startup`):

```python
        self.canvas = toga.Canvas(
            style=Pack(flex=1),
            on_resize=self.refresh_canvas,
            on_press=self.on_press,
            on_drag=self.on_drag,
            on_release=self.on_release,
            on_alt_press=self.on_alt_press,
            on_alt_drag=self.on_alt_drag,
            on_alt_release=self.on_alt_release
        )
```

- Note:  one can see similar `[iOS] Not implemented: Canvas`... errors for iOS with the the more complex sample:  https://github.com/beeware/toga/tree/master/examples/canvas (my sample is based on this one).

- Observe `briefcase dev` creates a running app, no errors.
- Observe `briefcase create macOS` creates a macOS app that runs, no errors.
- `briefcase create iOS`
- Open project in Xcode.
- Run with any simulator iOS device or real device running iOS.

Errors/stacktrace from Xcode (with a few identifiers snipped):

```
2020-12-06 16:07:09.576098-0800 DrawOnMe[89009:5232175] PythonHome is: <snipped>/DrawOnMe.app/Library/Python
2020-12-06 16:07:09.578325-0800 DrawOnMe[89009:5232175] PYTHONPATH is: PYTHONPATH=<snipped>/DrawOnMe.app/Library/Application Support/<snipped>/DrawOnMe.app/Library/Application Support/io.github.michhar.simple_drawing_program/app_packages
2020-12-06 16:07:09.578472-0800 DrawOnMe[89009:5232175] Initializing Python runtime...
2020-12-06 16:07:09.664885-0800 DrawOnMe[89009:5232175] Installing Python NSLog handler...
2020-12-06 16:07:09.769076-0800 DrawOnMe[89009:5232175] Running 'simple_drawing_program'...
2020-12-06 16:07:10.457244-0800 DrawOnMe[89009:5232175] App finished launching.
2020-12-06 16:07:10.497041-0800 DrawOnMe[89009:5232175] [iOS] Not implemented: Canvas.on_resize
2020-12-06 16:07:10.497322-0800 DrawOnMe[89009:5232175] [iOS] Not implemented: Canvas.set_on_press()
2020-12-06 16:07:10.497507-0800 DrawOnMe[89009:5232175] [iOS] Not implemented: Canvas.set_on_release()
2020-12-06 16:07:10.497686-0800 DrawOnMe[89009:5232175] [iOS] Not implemented: Canvas.set_on_drag()
2020-12-06 16:07:10.497866-0800 DrawOnMe[89009:5232175] [iOS] Not implemented: Canvas.set_on_alt_press()
2020-12-06 16:07:10.498025-0800 DrawOnMe[89009:5232175] [iOS] Not implemented: Canvas.set_on_alt_release()
2020-12-06 16:07:10.498189-0800 DrawOnMe[89009:5232175] [iOS] Not implemented: Canvas.set_on_alt_drag()
2020-12-06 16:07:10.528021-0800 DrawOnMe[89009:5232175] App became active.
```

**Expected behavior**

iOS build runs in a simulator from Xcode and on iOS-based devices as it does in dev mode and as a macOS app.

**Screenshots**
N/A

**Environment:**
 - Operating System:  macOS Catalina 10.15.7 (19H2)
 - Python version:
    ```
    Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    ```
 - Software versions:
   - Briefcase: `0.3.3`
   - Toga: `0.3.dev25`
 - Virtual environment with `venv`
- Xcode: Version 12.2 (12B45b)

**Additional context**

My `pyproject.toml` looks like (with a few identifiers snipped):

```yaml
[tool.briefcase]
project_name = "Simple Drawing Program"
bundle = "<snipped>"
version = "0.0.2"
url = "<snipped>"
license = "MIT license"
author = 'Micheleen Harris'
author_email = "<snipped>"

[tool.briefcase.app.simple_drawing_program]
formal_name = "DrawOnMe"
description = "Simple drawing program written in Python and packaged with Briefcase."
icon = "src/simple_drawing_program/resources/simple_drawing_program"
sources = ['src/simple_drawing_program']
requires = [
    'travertino==0.1.3',
    'toga==0.3.dev25',
]


[tool.briefcase.app.simple_drawing_program.macOS]
requires = [
    'toga-cocoa==0.3.dev25',
]

[tool.briefcase.app.simple_drawing_program.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.simple_drawing_program.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.simple_drawing_program.iOS]
requires = [
    'toga-iOS==0.3.dev25',
]

[tool.briefcase.app.simple_drawing_program.android]
requires = [
    'toga-android',
]
```

And I've defined class methods:

```python
    def refresh_canvas(self, widget):
        self.render_drawing()

    def on_press(self, widget, x, y, clicks):
        self.clicked_point = (x, y)
        self.render_drawing()

    def on_drag(self, widget, x, y, clicks):
        self.clicked_point = (x, y)
        self.render_drawing()

    def on_release(self, widget, x, y, clicks):
        self.clicked_point = None
        self.render_drawing()

    def on_alt_press(self, widget, x, y, clicks):
        self.clicked_point = (x, y)
        self.render_drawing()

    def on_alt_drag(self, widget, x, y, clicks):
        self.clicked_point = (x, y)
        self.render_drawing()

    def on_alt_release(self, widget, x, y, clicks):
        self.clicked_point = None
        self.render_drawing()
```

**Comment by freakboy3742** [comment] 2020-12-07 00:48
Thanks for the report. There's no real mystery here - the problem is exactly what the error message says. The features you're trying to use have not been implemented (yet!). Toga still in active development, and has a version number of 0.3; the completes of the APIs is reflected in that version number. 

We're not tracking these missing features as individual bugs because that would result in *hundreds* of open tickets them, and having all those open tickets won't actually help us implement features. Closing this ticket on that basis.

However, if you'd like to get involved with open source contribution, and this is a topic/feature that interests you, I'd encourage you to contribute a patch. The macOS and iOS implementations of Canvas share many common elements; you may find that many of the features that are currently marked as "not implemented" on iOS require an implementation that is very close to that already provided on macOS. If you'd like any pointers on contributing in this way, let us know.

**Closed by freakboy3742** 2020-12-07 00:48 UTC
Labels: bug

**Comment by michhar** [comment] 2020-12-07 00:53
Got it. :-)  Thanks for your quick response!  I'll definitely consider contributing - really nice project and have enjoyed learning it so far.
