### ISSUE TITLE
Linux GTK window content rendering issue on set_content

### ISSUE THREAD

**Issue by RPELLED** [beeware/toga#1754] opened 2023-01-24 22:58 UTC
### Describe the bug

A blank screen is showing when a showing window's content is set to a new box object

### Steps to reproduce

1. Create a simple app that manually sets the `main_window.content` (for example https://toga.readthedocs.io/en/latest/tutorial/tutorial-3.html)
2. On click of a button change the `main_window.content` to another box
3. `show()` the window
4. Click the button on a Linux machine (GTK)

### Expected behavior

After setting the window content, if the window is showing, the content should also be updated properly

### Environment

- Operating System: Ubuntu
- Python version: 3.8.10
- Software versions:
  - Briefcase: irrelevant
  - Toga: [version](https://github.com/beeware/toga/commit/08186396ae527bb6afbcf9f75d212538a0f35a86)
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment] 2023-01-24 23:00
I'm fairly sure this is a duplicate of #1439. If you've got additional details (such as a reproduction case that adds to what that ticket describes), please add them to that ticket.

**Closed by freakboy3742** 2023-01-24 23:00 UTC
Labels: bug
