### ISSUE TITLE
The issue of not appearing the icons in linux

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1052] opened 2020-09-19 11:31 UTC
In regard to icons in linux, as I was browsing the code, I found that finding the location of the icons in `Toga` depends on several things, which including that the `helloworld` parameter in command `python -m helloworld` must be a folder not a Python file, also `helloworld` must be treated as a module by using `-m` flag when executing the code, and the `lsoimportlib_metadata.metadata` also is defined, otherwise `Tog` will automatically rename my `app_name` and `module_name` as `toga` rather than my passed parameter `helloworld` and this will miss the execution the path to icons folder.

As I understand, because `Toga` is primarily a part of `BeeWare` project, I expect `BeeWare` will define these previous parameters correctly while creating the app, and exactly this is what happened when I am tried `tutorial-2` of `Toga` with `BeeWare`.

So, what do you think, is this an issue or can only alert the reader of this?

**Comment by freakboy3742** [comment] 2020-09-20 00:11
It sounds to me like what we have is "working as designed, but possibly buggy".

What the app *should* be doing is trying to do is find a folder that is "representive" of the app - which means the folder the app code is contained in. This, unfortunately, requires some guesswork and interpolation - and the code to do that guesswork is extremely difficult to test, because it *requires* starting a Python process in an isolated environment to truly duplicate what happens in the real world.

There are 4 ways to start a Python app:
1. `python helloworld.py`
2. `python -m helloworld` where helloworld is a file
3. `python -m helloworld` where helloworld is a folder
4. `python helloworld/helloworld.py`
 
These all have slightly different runtime behavior in terms of what happens to `sys.modules`. 

Toga also takes into account:
* The dist-info file for the installed app. This is produced by Briefcase.
* The `app_id`, `app_name`, and `module_name` arguments passed to the app itself.

It's entirely possible that we've missed some of the interactions of the startup modes and argument patterns.

@mshammel has been working on some tests for this behavior in #1028; there's still some work needed on that patch, but it will hopefully shake out some of the complications you've found.

So, what should we do? 

First, I think we need to get a good set of tests in place; #1028 is a good move in that direction. That will at least establish if there are buggy edge cases that need to be addressed.

We should also improve documentation around this problem; this is a complicated area of app operation, and documentation is the only way we're going to be able to make it less confusing.

**Comment by freakboy3742** [comment] 2022-03-29 07:12
Closing as the original question has been answered, and it's not clear what "resolution" of the issues raised would look like.

**Closed by freakboy3742** 2022-03-29 07:12 UTC
Labels: question
