### ISSUE TITLE
Toolbar shown in macOS app but not in iOS

### ISSUE THREAD

**Issue by Avagenzo** [beeware/toga#845] opened 2020-04-14 22:38 UTC
Following code looks great in macOS (building it with `briefcase build` and `briefcase` run). For some reason the screen on the ios emulator remains black when building it with `briefcase build iOS` and so on: 

```
def build(app):
    main_box = toga.Box(style=Pack(direction=COLUMN, padding_top=50))
    settings_icon = "icons/example.png"
    toolbar_grp: Group = toga.Group('Toolbar')

    settings_cmd = toga.Command(
        settings_action,
        label='Settings',
        tooltip='Change Settings',
        icon=settings_icon,
        group=toolbar_grp
    )

    app.commands.add(settings_cmd)
    app.main_window.toolbar.add(settings_cmd)
    return main_box

def settings_action(widget):
    print("Settings")

def main():
    """
    Function to call main function with title and startup method
    :return:
    """
    return toga.App('Example', startup=build)

if __name__ == '__main__':
    main().main_loop()
```

## Expected Behavior
I expected to see the same behaviour on both "systems".

## Current Behavior
Toolbar in MacOs app. Black Screen in iOS app

## Steps to reproduce
stated above

## Your Environment
Python 3.7
Ubuntu 19.10

* Toga Version (list the specific version number or git hash)
0.3.0.dev19
* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [x ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment] 2020-04-14 22:48
This is working as designed. Toga won't add a toolbar on iOS, because iOS doesn't have a native concept of a toolbar. 

This is part of the underlying philosophy of Toga as a framework: capturing the underlying *idea* of the app, and rendering it in a platform appropriate way. For this reason, iOS apps won't have menu bars, either.

In this particular instance, it looks like you are trying to add a "setting" option - which *does* have a native representation in iOS. Capturing "app settings" is something on our Todo list - because every platform has a distinct way that the render and store settings. There was some initial discussion about this on #90; however, there hasn't been any progress on that ticket for a while.

I'm going to close this specific ticket on the basis that the original question/feature you asked is a "wontfix"/"works as designed"; however, if you want to discuss this idea further, feel free to keep the discussion going on.

**Closed by freakboy3742** 2020-04-14 22:48 UTC

**Comment by Avagenzo** [comment] 2020-04-14 22:59
Thank you for the clarification.
