### ISSUE TITLE
1st Tutorial button does not display unless window sized right.

### ISSUE THREAD

**Issue by keshto** [beeware/toga#929] opened 2020-05-30 23:29 UTC
## Expected Behavior
Button to be visible and clickable in most window sizes

## Current Behavior
Button's visibility is dependent on select window sizes and even then might not be clickable, because behind the menu bar.
![Screenshot](https://user-images.githubusercontent.com/766237/83340871-ee89b980-a278-11ea-80ce-0298aa2b881b.png)

## Steps to reproduce
1.  use code from https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html
2. python -savedFile.py-

## Your Environment
* Python Version (list the specific version number)
> python --version
Python 3.8.3

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [X] Linux - distro:  VoidLinux  - version: rolling
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
Requirement already satisfied: toga in /lib/python3.8/site-packages (0.3.0.dev19)

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [X] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment] 2020-05-31 01:40
Thanks for the report. This looks like it's a duplicate of #139, which was resolved really recently; the fix is availalbe in the development version right now, and will be in the 0.3.0.dev20 release.

**Closed by freakboy3742** 2020-05-31 01:40 UTC
