### ISSUE TITLE
Tutorial 1  :   [Winforms] Not implemented: TextInput.set_font()

### ISSUE THREAD

**Issue by mc436572** [beeware/toga#577] opened 2018-08-10 02:34 UTC
## Current Behavior
when run Tutorial 1 ,    [Winforms] Not implemented: TextInput.set_font(),   
app can run ,  but  ,  layout is wrong
![image](https://user-images.githubusercontent.com/23473125/43935950-e13ed0dc-9c88-11e8-9f3c-4ad723e0a2f8.png)
![image](https://user-images.githubusercontent.com/23473125/43935958-ea9ebf7a-9c88-11e8-9006-2bbe1d00919e.png)

## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] Windows - 10:

* Toga Target (the type of app you are trying to generate)
 

  - [ ] winforms 
  - [ ] win32

**Comment by danyeaw** [comment] 2018-09-10 00:47
@mc436572 Thanks for the issue report. Not implemented warnings are expected, they mean certain portions of the windows backend aren't yet implemented. It isn't an error, it just means things are finished yet. You also mentioned that layout is wrong, but the picture you posted looks like things are layed out pretty good. Can you elaborate on what you were expecting?

**Comment by freakboy3742** [comment] 2020-04-25 09:47
Closing on the basis this is "working as intended" - raising a warning that a feature isn't available; combined with the fact the feature *is* now implemented.

**Closed by freakboy3742** 2020-04-25 09:47 UTC
