### ISSUE TITLE
Toga demo cannot install on Windows with Python 3.8

### ISSUE THREAD

**Issue by ghost** [beeware/toga#903] opened 2020-05-12 20:44 UTC
## Expected Behavior
Install toga-demo

## Current Behavior
``` ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-h9n2linw\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-h9n2linw\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\****\AppData\Local\Temp\pip-record-l1lqd2bo\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python38\Include\pythonnet'
         cwd: C:\Users\****\AppData\Local\Temp\pip-install-h9n2linw\pythonnet\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-h9n2linw\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\****\\AppData\\Local\\Temp\\pip-install-h9n2linw\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\****\AppData\Local\Temp\pip-record-l1lqd2bo\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python38\Include\pythonnet' Check the logs for full command output.
```

## Steps to reproduce

1. (With a fresh install of windows and .net 4.8) 
```
pip install --upgrade setuptools wheel
pip install --pre toga-demo
```

## Your Environment

* Python Version (list the specific version number)
3.8.3rc1

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: Windows 10 Build 18363
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
v0.2.15
* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment] 2020-05-12 23:33
Thanks for the report. 

In this case, the issue isn't with Toga; it's with one of Toga's dependencies. [Python.net](https://github.com/pythonnet/pythonnet/) hasn't been updated for Python 3.8; unfortunately, it's difficult for us to annotate the package itself with anything helpful here, because the package works fine on Linux and macOS.

I'll leave this open as a documentation bug; we should add a note on the getting started page about the Python3.8 limitation on Windows. The [BeeWare tutorial already has a note to this effect](https://docs.beeware.org/en/latest/tutorial/tutorial-0.html).

**Comment by RishabhAgarwal-2001** [comment] 2020-06-06 14:29
@freakboy3742 Can I take the task of updating the docs?

**Comment by saroad2** [comment] 2020-09-28 08:35
Python 3.8 is now supported by Python.net, therefore, closing this issue.

**Closed by saroad2** 2020-09-28 08:35 UTC
Labels: bug, first-timers-only, up-for-grabs
