### ISSUE TITLE
Add an icon or user image to Android AppBar, change color, and Hide it when necessary.

### ISSUE THREAD

**Issue by thiwtzsch** [beeware/toga#2349] opened 2024-01-17 08:22 UTC
### What is the problem or limitation you are having?

The Android AppBar is amazing as it is but for Webviews it is essential to hide the AppBar for better view. When using it for normal MainWindows there should be an option to add, remove or change the avatar. This widget behaviour is observed when using the title of the MainWindow. You can change it at any instance.

### Describe the solution you'd like

Use the icon function of the toga.App.
Allow the App to change the icon and update screen.
Add the Hide AppBar or Show Bar options. The user can use the functions on their menu or other available widgets
Assign and/or update theme color for the app and AppBar 

### Describe alternatives you've considered

My alternative was using webview and flask. 
However, I was forced to design around the AppBar theme.

**Comment by freakboy3742** [comment] 2024-01-18 05:52
I'm not entirely clear what the reference to WebView has to do with this request, but the underlying "hiding the AppBar" request is a duplicate of #1870. This has been a source of discussion recently, with a prototype implementation available in #2244.

**Closed** 2024-01-18 05:52 UTC
Labels: enhancement
