### ISSUE TITLE
Cant make the window smaller

### ISSUE THREAD

**Issue by software-made-easy** [beeware/toga#1380] opened 2021-12-12 11:22 UTC
**I can't make the window smaller**
I have set button.style.flex to 1 and when I enlarge the window, the button also enlarges, as far as it is good. But then afterwards I have the problem that I cannot make the window smaller again

https://user-images.githubusercontent.com/58736434/145710224-e2752de9-bf77-4589-adfc-38827fdb6827.mp4

**Environment:**
 - Operating System: Linux Mint 20.2
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev29

**Comment by freakboy3742** [comment] 2021-12-12 22:05
Thanks for the report. I believe this is a Linux specific bug; the window is determining it's layout using the existing window size, and then enforcing that as a minimum window size. This means you can *expand* a window, but once expanded, it can't contract.

**Comment by freakboy3742** [comment] 2022-03-29 07:54
Closing as a duplicate of #1205

**Closed by freakboy3742** 2022-03-29 07:54 UTC
Labels: bug, up-for-grabs, linux
