### ISSUE TITLE
setting self.main_window.content, in method other than startup(), freezes app on iOS

### ISSUE THREAD

**Issue by calvma** [beeware/toga#1287] opened 2021-06-17 18:21 UTC
**Describe the bug**
The UI completely freezes when setting `self.main_window.content` anywhere other than the `startup()` method on iOS. This code philosophy works great on macOS with `briefcase dev` and on Android, so not sure what's different about iOS. There is no stack trace in xcode

**To Reproduce**
1. In a button callback method, set `self.main_window.content` to a freshly instantiated Box widget with children
2. Run app on iOS and click button

**Expected behavior**
Re-setting `self.main_window.content` dynamically works great on Android, but not on iOS for some reason. I was able to successfully 're-set' self.main_window.content on iOS before by removing and adding children to a class var, `self.main_box`, and calling `self.main_window.content. = self.main_box` in `startup()`. I'm hoping to find a way of refreshing content to simulate multiple views that works on both Android and iOS

**Screenshots**
NOTE that the screen goes black around the boxes in the simulator. This pixel color change did not happen on an actual device, but I'm hoping it may be a clue!

![image](https://user-images.githubusercontent.com/22796161/122451219-be34bc00-cf5c-11eb-9d03-f5fbeebe489a.png)
I also tested on an actual iPhone 6s on iOS 14.5 and the app froze as well

**Environment:**
 - Operating System: MacOS Big Sur 11.4
 - Python version: 3.7
 - Software versions:
   - Briefcase: latest
   - Toga: latest

**Additional context**

**Comment by freakboy3742** [comment] 2022-03-29 07:46
Possible duplicate of #1161.

**Comment by freakboy3742** [comment] 2022-03-29 08:01
Closing as a duplicate of #1439, which is a unified "fix main content replacement" ticket.

**Closed by freakboy3742** 2022-03-29 08:01 UTC
Labels: bug, up-for-grabs, iOS
