### ISSUE TITLE
`uv add toga` on MacOS erroneously builds `pygobject` for linux

### ISSUE THREAD

**Issue by abulka** [beeware/toga#2995] opened 2024-11-25 05:47 UTC
### Describe the bug

`uv add toga` or `uv add toga-demo` on MacOS fails. It tries to build `pygobject` (which is a linux thing) and fails. Interestingly `uv pip install toga` works correctly.

### Steps to reproduce

1. Create a new directory
2. Issue the commands
```
uv init --python 3.12
uv sync
uv add toga
```
3. See failure error
Notice uv tries to download and build `pygobject` which is GTK for linux, and should not be happening on a Mac!

```
% uv add toga
  × Failed to download and build `pygobject==3.50.0`
  ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1)
  ...
  help: `pygobject` (v3.50.0) was included because `py-15-toga-py12` (v0.1.0) depends on `toga` (v0.4.8) which depends
        on `toga-gtk==0.4.8` (v0.4.8) which depends on `pygobject>=3.50.0`
```

### Expected behavior

Expect successful installation of toga wheel without needing `pygobject` .

### Environment

- Operating System: MacOS 15.1.1
- Python version: 3.12
- Software versions:
  - Toga: latest

### Logs

```
% uv add toga
  × Failed to download and build `pygobject==3.50.0`
  ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1)

      [stdout]
      + meson setup /Users/andy/.cache/uv/sdists-v6/pypi/pygobject/3.50.0/cSgYGol3pHG6adtW916RT/src
      /Users/andy/.cache/uv/sdists-v6/pypi/pygobject/3.50.0/cSgYGol3pHG6adtW916RT/src/.mesonpy-qhu3xuzk
      -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback
      --native-file=/Users/andy/.cache/uv/sdists-v6/pypi/pygobject/3.50.0/cSgYGol3pHG6adtW916RT/src/.mesonpy-qhu3xuzk/meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: /Users/andy/.cache/uv/sdists-v6/pypi/pygobject/3.50.0/cSgYGol3pHG6adtW916RT/src
      Build dir: /Users/andy/.cache/uv/sdists-v6/pypi/pygobject/3.50.0/cSgYGol3pHG6adtW916RT/src/.mesonpy-qhu3xuzk
      Build type: native build
      Project name: pygobject
      Project version: 3.50.0
      C compiler for the host machine: cc (clang 16.0.0 "Apple clang version 16.0.0 (clang-1600.0.26.4)")
      C linker for the host machine: cc ld64 1115.7.3
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Program python3 found: YES (/Users/andy/.cache/uv/builds-v0/.tmphEIS5m/bin/python)
      Found pkg-config: YES (/opt/homebrew/bin/pkg-config) 2.3.0
      Run-time dependency python found: YES 3.12
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig, framework and cmake)
      Not looking for a fallback subproject for the dependency gobject-introspection-1.0 because:
      Use of fallback dependencies is disabled.

      ../meson.build:31:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found.

      A full log can be found at
      /Users/andy/.cache/uv/sdists-v6/pypi/pygobject/3.50.0/cSgYGol3pHG6adtW916RT/src/.mesonpy-qhu3xuzk/meson-logs/meson-log.txt

  help: `pygobject` (v3.50.0) was included because `py-15-toga-py12` (v0.1.0) depends on `toga` (v0.4.8) which depends
        on `toga-gtk==0.4.8` (v0.4.8) which depends on `pygobject>=3.50.0`
```

### Additional context

Workarounds:

1. `brew install pygobject3` before `uv add toga` solves the dependency and allows `uv add toga` to succeed. However this should not be needed on a Mac, as GTK is not relevant on Mac.
2. Alternatively, a different way of installing toga via `uv pip install toga` works. This avoids the workspace level `uv add toga` approach.

May be related to https://github.com/astral-sh/uv/issues/7985

**Comment by freakboy3742** [comment] 2024-11-25 23:06
Ok - I've got to the bottom of this. It's... not *entirely* uv's fault :-)

While it appears that `uv` is trying to *install* pygobject, it's not - it's trying to resolve pyobject's dependencies.

When you use `uv add`, it builds a lock file for *all* possible platforms (because the lock file is intentionally cross-platform). toga-gtk has a dependency on pygobject. The problem is that pygobject is a binding to the GObject libraries, but these libraries aren't part of the many manylinux spec - so pygobject *can't* be packaged as a wheel. This means the only distribution on PyPI is a source tarball.

However, because it's only available as a source tarball, the only way for uv to determine pygobject's dependencies is to... build the wheel from source. Which it can't do on macOS... and hilarity ensues.

The same problem exists for pycairo, but the install is failing before that point in the install is reached.

The fix (which is alluded to in the last bullet point of [this comment](https://github.com/astral-sh/uv/issues/7985#issuecomment-2399837275), is for the project to provide the metadata for the package that can't be resolved. 

At time of writing, adding the following to the `pyproject.toml` before running `uv add toga`:
```
[tool.uv]
dependency-metadata = [
    { name = "pygobject", version = "3.50.0", requires-dist = [], requires-python = ">=3.9" },
    { name = "pycairo", version = "1.27.0", requires-dist = [], requires-python = ">=3.9" },
]
```

The only part I'm not clear about is why adding a [resolver environment](https://docs.astral.sh/uv/reference/settings/#environments) doesn't seem to constrain the resolution process. The documentation seems to suggest that it should... but experience seems to demonstrate otherwise.

It appears that adding this `tool.uv` declaration to the `pyproject.toml` for `toga-gtk` may be a possible resolution - but I'm not completely convinced that this isn't an artefact of caching on my machine (i.e., since the build has succeeded once on my machine, uv has cached everything that is required to resolve future builds).

**Comment by freakboy3742** [comment] 2024-11-27 00:54
Follow up - adding `[tool.uv]` to `toga-gtk` *can't* work - because the only artefact of `toga-gtk` that `uv` has access to is the wheel metadata, which won't include the content of `pyproject.toml`.

**Comment by ncoghlan** [comment] 2024-12-01 08:21
I added https://github.com/astral-sh/uv/issues/9548 for this, since it's a general issue with making cross-platform resolution to work, and in theory calling `prepare_metadata_for_build_wheel` instead of calling `build_wheel` *should* work, but:

* I'm not sure if `uv` is trying that first and then falling back to `build_wheel`, or skipping straight to the latter
* if `uv` is trying the metadata-only build before falling back to the full build, the fact `prepare_metadata_for_build_wheel` isn't working may either be a general issue with `meson-build`, or else a specific issue with the way `pygobject` is using `meson-build`

**Comment by ncoghlan** [comment] 2024-12-01 09:24
I mentioned this to @konstin, and https://github.com/astral-sh/uv/pull/9549 should fix it.

**Comment by freakboy3742** [comment] 2024-12-04 23:07
Looks like uv has merged a fix for this; leaving this open until there's a release including the fix so we can verify it works.

**Comment by ncoghlan** [comment] 2024-12-07 17:10
uv 0.5.7 has been published with the fix

**Comment by freakboy3742** [comment] 2024-12-08 05:41
Confirming that the workflow described in the ticket now works, without any additional metadata. Closing this ticket on that basis.

**Closed by freakboy3742** 2024-12-08 05:41 UTC
Labels: bug
