### ISSUE TITLE
iOS: App freezes after switching content

### ISSUE THREAD

**Issue by t-arn** [beeware/toga#1161] opened 2020-12-09 12:29 UTC
I'm trying to create a mobile app with more than just 1 page. 
For Android, this works fine by replacing the content of the main window:
`self.app.main_window.content = new_main_box`
It also works on macOS.

On iOS, the new_main_box is also shown, but then, the UI is completely unresponsive. No button is working, no input field is taking the focus, nothing works anymore and I have to kill the app to get out of this screen.
There is no error in the logs, so I have no idea what the problem might be.

I made a minimal demo app to show this problem:
https://bitbucket.org/TomArn/demoapp.git   branch: iOS_content_switching
In this demo app, in addition to the above problem, the new screen is black and I only see the button, but not the label, whereas in the other app where I first found the problem, the screen actually looked pretty OK (except that it was frozen....)

I'm using Python 3.8 on iOS 14.4, Toga 0.3.0dev27

**Comment by mshammel** [comment] 2021-02-06 18:53
One workaround for this is to set the main_window's content to a persistent box, and then swap out the contents of that box rather than the box itself.

For example, I modified your demoapp app.y (attached) and this works for me under the iOS simulator.

[app.py.zip](https://github.com/beeware/toga/files/5937437/app.py.zip)

**Comment by t-arn** [comment] 2021-02-10 07:15
@mshammel Many thanks for your workaround! I can confirm that it is working on iOS :-)
I also tested the workaround on Android, but there, I get following error:
```
2021-02-10 08:00:53.874 5279-5279/com.t_arn.demoapp E/Python: Traceback (most recent call last):
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:   File "/data/user/0/com.t_arn.demoapp/files/python/user_code/app_packages/rubicon/java/api.py", line 44, in dispatch
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:     val = getattr(pyinstance, method)(*args)
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:   File "/data/user/0/com.t_arn.demoapp/files/python/user_code/app_packages/toga_android/widgets/button.py", line 14, in onClick
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:     self.button_impl.interface.on_press(widget=self.button_impl.interface)
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:   File "/data/user/0/com.t_arn.demoapp/files/python/user_code/app_packages/toga/handlers.py", line 55, in _handler
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:     result = handler(interface, *args, **kwargs)
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:   File "/data/user/0/com.t_arn.demoapp/files/python/user_code/app/demoapp/app.py", line 39, in handle_btn_goto1
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:     self.box.remove(self.box.children[0])
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:   File "/data/user/0/com.t_arn.demoapp/files/python/user_code/app_packages/toga/widgets/base.py", line 135, in remove
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python:     self._impl.remove_child(child._impl)
2021-02-10 08:00:53.875 5279-5279/com.t_arn.demoapp E/Python: AttributeError: 'Box' object has no attribute 'remove_child'
```
So, unfortunately, your workaround does not cover both mobile platforms, which means that in my app code I would need to treat iOS specifically with `if platform == 'iOS' `

**Comment by calvma** [comment] 2021-06-22 16:58
how can we detect what platform the toga app is currently running on?

**Comment by freakboy3742** [comment] 2021-06-22 22:42
@calvma `toga.platform.current_platform` contains the currently active platform (as a string; you're looking for `iOS` in this case).

**Comment by t-arn** [comment] 2021-11-13 09:23
@freakboy3742 I just re-tested this issue with the latest toga  release 0.3.0.dev30 and sadly, it still exists :-(

**Comment by freakboy3742** [comment] 2022-03-29 08:01
Closing as a duplicate of #1439, which is a unified "fix main content replacement" ticket.

**Closed by freakboy3742** 2022-03-29 08:01 UTC
Labels: bug, up-for-grabs, iOS
