### ISSUE TITLE
[QUERY] How to do `save_file_dialog` on Android?

### ISSUE THREAD

**Issue by vzool** [beeware/toga#2718] opened 2024-07-20 06:57 UTC
This code works just fine with Android 15 for `open_file_dialog`:
```python
async def openFileDialog(self, widget):
    from toga.platform import current_platform
    print("current_platform : ", current_platform)
    if current_platform == "android":
        from android.content import Intent

        fileChose = Intent(Intent.ACTION_GET_CONTENT)
        fileChose.addCategory(Intent.CATEGORY_OPENABLE)
        fileChose.setType("*/*")

        # Assuming `app` is your toga.App object
        results = await self._impl.intent_result(Intent.createChooser(fileChose, "Choose a file"))
        data = results['resultData'].getData()
        context = self._impl.native
        bytesJarray = bytes((context.getContentResolver().openInputStream(data).readAllBytes()))
        # will do something to get filePath and return filePath
       file_path = os.path.join(self.paths.cache, 'import_file')
       with open(file_path, "wb") as file:
           file.write(bytesJarray)
    else:
        filePath = await self.main_window.open_file_dialog("打开文件")
    return filePath
```
How can I use `save_file_dialog` on Android?
Thanks

_Originally posted by @vzool in https://github.com/beeware/toga/discussions/1990#discussioncomment-10100603_

**Comment by freakboy3742** [comment] 2024-07-20 07:11
Closing as this is a question, not a bug or feature request, and was originally posted as such.

**Closed by freakboy3742** 2024-07-20 07:11 UTC
